### ISSUE TITLE
vncserver uses random session number if lock files not found

### ISSUE THREAD

**Issue by kim0** [TigerVNC/tigervnc#781] opened 2018-12-26 15:53 UTC
I kept hitting this problem for unknown reasons. The below is as close as I could get to creating a reproducible case. AFAICT, the main flaw is that when I start vncserver with a particular session number (:21 here), it should **never** choose to run over another randomly chosen session number!

However, below when the lock files are not found (in reality, probably bec of nfs4 locking failure in my case afaict!) vncserver picks a random session number and proceeds with it. IMO this should **never** be allowed to happen. 

PS: This is probably related to what @atesin was hitting in https://github.com/TigerVNC/tigervnc/issues/527

Thanks

```
[myuser@sim-0 ~]$ vncserver :21

New 'sim-0.corp.mycompany.com:21 (myuser)' desktop is sim-0.corp.mycompany.com:21

Starting applications specified in /home/myuser/.vnc/xstartup
Log file is /home/myuser/.vnc/sim-0.corp.mycompany.com:21.log

[myuser@sim-0 ~]$ rm -rf /tmp/.X21-lock
[myuser@sim-0 ~]$ rm -rf /tmp/.X11-unix/X21
[myuser@sim-0 ~]$ vncserver :21
A VNC server is already running as :21

New 'sim-0.corp.mycompany.com:46 (myuser)' desktop is sim-0.corp.mycompany.com:46

Starting applications specified in /home/myuser/.vnc/xstartup
Log file is /home/myuser/.vnc/sim-0.corp.mycompany.com:46.log
```

**Comment by CendioOssman** [comment] 2018-12-28 12:22
I'm afraid I cannot reproduce this issue. Are you perhaps using a modified version of `vncserver`? Where did you get it? From us or your distribution?

**Comment by CendioOssman** [comment] 2019-01-11 14:31
This seems to be the result of some modified `vncserver` and not ours, so closing.

**Comment by kim0** [comment] 2019-01-11 16:58
@CendioOssman .. Thanks .. you can find it here https://transfer.sh/14RLmq/vncserver

**Comment by CendioOssman** [comment] 2019-01-16 12:53
I'm sorry, but that file does not match the files from our packages on bintray. I also cannot find anything in the git history suggesting it ever looked like that.

Could you run `rpm -qi tigervnc-server`? It should tell us more about where that package comes from.

**Comment by kim0** [comment] 2019-01-16 13:39
@CendioOssman .. Thanks! Please find the output from rpm below. My understanding was always that tigervnc started at Redhat, so installing from the official redhat repos, was "official" to me. I see now you're saying official = bintray. Sorry if my answer was misleading. Should I try filing bugs on RedHat for this? Would using rpms from bintray resolve this issue possibly?

```
# rpm -qi tigervnc-server
Name        : tigervnc-server
Version     : 1.8.0
Release     : 13.el7
Architecture: x86_64
Install Date: Tue 11 Dec 2018 07:53:05 PM UTC
Group       : User Interface/X
Size        : 520736
License     : GPLv2+
Signature   : RSA/SHA256, Mon 03 Sep 2018 08:18:37 PM UTC, Key ID 199e2f91fd431d51
Source RPM  : tigervnc-1.8.0-13.el7.src.rpm
Build Date  : Fri 31 Aug 2018 12:04:17 PM UTC
Build Host  : x86-037.build.eng.bos.redhat.com
Relocations : (not relocatable)
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : http://www.tigervnc.com
Summary     : A TigerVNC server
Description :
The VNC system allows you to access the same desktop from a wide
variety of platforms.  This package includes set of utilities
which make usage of TigerVNC server more user friendly. It also
contains x0vncserver program which can export your active
X session.
#
# rpm -V tigervnc-server
# 
```

**Comment by CendioOssman** [comment] 2019-01-16 15:57
> @CendioOssman .. Thanks! Please find the output from rpm below. My understanding was always that tigervnc started at Redhat, so installing from the official redhat repos, was "official" to me. I see now you're saying official = bintray. Sorry if my answer was misleading.

No worries. The maintainer of the Red Hat package was with us when this project started, but it was mostly a push from us here at Cendio. But even so the project is independent and both Red Hat and Cendio ship versions that are modified in various ways.

> Should I try filing bugs on RedHat for this?

Yes, only they can resolve this.

> Would using rpms from bintray resolve this issue possibly?

It should. But I cannot say what other Red Hat modifications you'll lose and what the consequences are. I suggest you try it, but be ready to revert if things go bad.

**Closed by CendioOssman** 2019-01-16 15:57 UTC
