### ISSUE TITLE
Selection in some server side tools causes client to trigger windows 10 default beep

### ISSUE THREAD

**Issue by fnJeff** [TigerVNC/tigervnc#1215] opened 2021-03-09 14:11 UTC
**Describe the bug**
To be clear, I'm not sure if this is a TigerVNC bug or not, but I'm not sure where else to start.  I was in the process of switching from using xemacs to gnu emacs.  I was checking the region highlight color against each other, which involved highlighting chunks of text in both editors.  Seemingly randomly I kept hearing a dinging sound being played.  So I started experimenting in an attempt to narrow it down.  Highlighting (selecting) a region in xemacs *never* causes this beep sound.  Highlighting a region in emacs (gnu) intermittently does cause the beep sound.

At first I though this was the unix system bell, but it is not.  When I open the TigerVNC options menu and disable "Accept clipboard from server" the beep sound never happens.  Of course, this kills the ability to copy and paste from the server to windows, which isn't an acceptable solution.  But it did point towards what was causing it and also that it was probably the windows default beep, not unix.  I brought up windows sounds config and verified that the "Default beep" setting was indeed the same sound I was hearing.  When I set "Default beep" to "none", I would no longer hear the sound while highlighting in emacs.

So it seems that for whatever reason, when I am highlighting text in emacs (never experienced this with any other tool before now) it is doing something with the text copied to the clipboard that TigerVNC is passing through to windows clipboard that is causing the window "Default beep" to trigger.

As this is hard to describe in words, I captured a short video that shows the windows sound config dialog box, the TigerVNC clipboard viewer, and a section of the VNC session showing both emacs and xemacs windows.  As I highlight text in emacs, you can hear when the sound occurs as well as see the text in the TigerVNC clipboard viewer.  It doesn't seem to be related to what text I highlight, at least not that I have noticed.  It also didn't seem to be mouse related, as I also tried holding shift and then paging down through text to highlight it.  It does seem to be related to a quantity of what is highlighted.  I could not get it to beep when double-click highlighting one word over and over, or even highlighting only a couple words over and over.  It seems like some threshold is hit and maybe the clipboard contents are passed to windows or flushed or something.

**To Reproduce**
I'm hoping the video helps to show what might be used to reproduce.

**Expected behavior**
I don't expect to have the windows beep firing randomly as I highlight text.

**Screenshots**
Video capture attached.  Shows version of TigerVNC java client and both emacs and xemacs.

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNC Java client
 - VNC client version: 1.10.1
 - Client downloaded from: your release area on github

**Server (please complete the following information):**
 - OS: Linux xxxx 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - VNC server: Not sure, managed by IT
 - VNC server version: Not sure, managed by IT
 - Server downloaded from: Not sure, managed by IT
 - Server was started using: Not sure, managed by IT

**Additional context**

Had to split the video into 3 parts to upload it.

https://user-images.githubusercontent.com/31246517/110482887-70045700-80e9-11eb-89e8-37552e0a508e.mp4
https://user-images.githubusercontent.com/31246517/110482909-7561a180-80e9-11eb-835c-70501245b86e.mp4
https://user-images.githubusercontent.com/31246517/110482924-798dbf00-80e9-11eb-96c6-e3dc4b22824e.mp4

**Comment by fnJeff** [comment] 2021-03-09 14:25
I just downloaded 1.11.0 versions of both the native and java clients.

Java client still exhibits this issue, although it seems like slightly less often.  The sound is now crackly, which doesn't make sense.  This version seems to have some weird black outline around the mouse cursor that wasn't there in 1.10.1.

Native client does not have this issue.  I hope this is a giant clue that helps to narrow in on what is causing this.

**Comment by bphinz** [comment] 2021-03-09 17:12
I am able to reproduce this and will try to track down the cause

**Comment by bphinz** [comment] 2021-03-12 00:33
Fixed in d2f18924

**Closed by bphinz** 2021-03-12 00:33 UTC

**Comment by fnJeff** [comment] 2021-03-12 08:33
You're a rockstar Brian, thanks!

Any idea when you expect the next stable release with this fix?
