### ISSUE TITLE
Service crashes on Windows 10 Home x64

### ISSUE THREAD

**Issue by dotnerdify** [TigerVNC/tigervnc#187] opened 2015-08-15 02:12 UTC
Attempting to launch winvnc4.exe -noconsole -service_run in command prompt as administrator crashes the process.

Process winvnc4.exe dies immediately after and leaves a log message on EventViewer:
Faulting application name: winvnc4.exe, version: 1.5.0.0, time stamp: 0x352c2241
Faulting module name: ntdll.dll, version: 10.0.10240.16430, time stamp: 0x55c59f92
Exception code: 0xc0000374
Fault offset: 0x00000000000ea28c
Faulting process id: 0x1164
Faulting application start time: 0x01d0d6fe24662c54
Faulting application path: C:\Program Files\TigerVNC\winvnc4.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 1a656fa9-bb67-47f4-862e-d046e4256525
Faulting package full name: 
Faulting package-relative application ID:

**Comment by CendioOssman** [comment] 2015-08-17 07:31
Does it work in user mode?

**Comment by dotnerdify** [comment] 2015-08-17 14:08
I'm unsure, will try it at home. Is the crash dump helpful?

**Comment by CendioOssman** [comment] 2015-08-17 14:24
Sorry, no. The address is inside a system DLL so it won't help us. A full back trace would be useful, but I don't think you can get that from the official builds. I think you might have to wait until a developer has a Windows 10 machine and can test.

**Comment by deadcowfr** [comment] 2015-08-19 00:31
For what it's worth, exact same error.

**Comment by CendioOssman** [comment] 2015-08-20 13:37
Thanks, that at least shows that the problem isn't in the service code.

Could you start the server with the arguments `-Log *:file:100`? You'll get a log file at `c:\temp\winvnc4.log`. Perhaps the last few lines will give a clue what the problem is.

**Comment by deadcowfr** [comment] 2015-08-20 17:09
Thu Aug 20 19:09:15 2015
 Config:      set immutable Log
 VNCServerST: creating single-threaded server PC
 Threading:   created          Native(000000000146EEF0)
 Threading:   created          TrayIcon(0000000002BA9A80)
 Registry:    duplicated FFFFFFFF80000001 to FFFFFFFF80000001
 Threading:   started          TrayIcon(0000000002BA9A80)
 Registry:    createKey(FFFFFFFF80000001,Software\TigerVNC\WinVNC4) =
              00000000000001C8
 Registry:    RegCloseKey(FFFFFFFF80000001)
 RegConfig:   registry changed
 MsgWindow:   creating window "VNCTray"
 ManagedListener: set server to 000000000024F640
 ManagedListener: set port to 5900
 MsgWindow:   null _this in 0000000000200ABA, message 24
 MsgWindow:   null _this in 0000000000200ABA, message 81
 MsgWindow:   null _this in 0000000000200ABA, message 83
 ManagedListener: set server to 000000000024F8A8
 ManagedListener: set port to 5800
 ManagedListener: set filter to +
 ManagedListener: set filter to +
 VNCServerWin32: Refreshing tray icon
 MsgWindow:   created window "VNCTray" (0000000000200ABA)

**Comment by dotnerdify** [comment] 2015-08-20 17:39
Note: the instructed -Log option does not create a file if c:\temp directory doesn't exist.

running "winvnc4.exe -noconsole -service_run -Log *:file:100":


Thu Aug 20 13:38:43 2015
 Config:      set immutable Log
 VNCServerST: creating single-threaded server DESKTOP-V923QLB
 Threading:   created          Native(0000000000CBBF00)
 Threading:   created          TrayIcon(000000000164ED80)
 Registry:    duplicated FFFFFFFF80000002 to FFFFFFFF80000002
 Threading:   started          TrayIcon(000000000164ED80)
 Registry:    createKey(FFFFFFFF80000002,Software\TigerVNC\WinVNC4) =
              00000000000001D0
 Registry:    RegCloseKey(FFFFFFFF80000002)
 RegConfig:   registry changed
 ManagedListener: set server to 000000000024F640
 ManagedListener: set port to 5900
 MsgWindow:   creating window "VNCTray"
 MsgWindow:   null _this in 00000000000F05A2, message 24
 MsgWindow:   null _this in 00000000000F05A2, message 81
 ManagedListener: set server to 000000000024F8A8
 ManagedListener: set port to 5800
 ManagedListener: set filter to +
 ManagedListener: set filter to +
 VNCServerWin32: Refreshing tray icon
 MsgWindow:   null _this in 00000000000F05A2, message 83
 MsgWindow:   created window "VNCTray" (00000000000F05A2)

**Comment by TheFiZi** [comment] 2015-08-22 23:45
I'm having the same issue with Windows 10 Pro 64-bit.

Dug through the event viewer and found this:

	Log Name:      System
	Source:        Service Control Manager
	Date:          8/22/2015 4:31:45 PM
	Event ID:      7030
	Task Category: None
	Level:         Error
	Keywords:      Classic
	User:          N/A
	Computer:      centi
	Description:
	The Provides remote access to this machine via the VNC/RFB protocol. service is marked as an interactive service.  However, the system is configured to not allow interactive services.  This service may not function properly.
	Event Xml:
	<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	  <System>
	    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
	    <EventID Qualifiers="49152">7030</EventID>
	    <Version>0</Version>
	    <Level>2</Level>
	    <Task>0</Task>
	    <Opcode>0</Opcode>
	    <Keywords>0x8080000000000000</Keywords>
	    <TimeCreated SystemTime="2015-08-22T23:31:45.674613600Z" />
	    <EventRecordID>1157</EventRecordID>
	    <Correlation />
	    <Execution ProcessID="584" ThreadID="1716" />
	    <Channel>System</Channel>
	    <Computer>centi</Computer>
	    <Security />
	  </System>
	  <EventData>
	    <Data Name="param1">Provides remote access to this machine via the VNC/RFB protocol.</Data>
	  </EventData>
	</Event>

So then I followed this: https://support.software.dell.com/netvault-backup/kb/116150

Did not solve the problem. Constant crashes continue.

**Comment by CendioOssman** [comment] 2015-09-28 08:02
Urgh. Some kind of memory corruption, and I'm having a hard time pinpointing what causes it.

**Comment by CendioOssman** [comment] 2015-09-29 13:48
Shoddy memory management. Fixed in f7aa3f9bd315ba52d6ee1e7236a580102c8d20b8.

**Closed** 2015-10-06 13:03 UTC
Labels: bug
