### ISSUE TITLE
Since v1.14 TigerVNC Viewer is no longer able to connect to TightVNC Server

### ISSUE THREAD

**Issue by t4n1s** [TigerVNC/tigervnc#1858] opened 2024-10-25 13:36 UTC
**Describe the bug**
Have been using TigerVNC viewer to connect to tight VNC server for years now. Since my last update to release 1.14, I'm no longer able to connect to my TightVNC server using TigerVNC viewer.

Error message:
No matching security types.

**To Reproduce**
1. Install TightVNC Server on Windows 11 Pro as a Service.
2. Open TigerVNC Viewer and try to connect to TightVNC Server.
3. Error message appears.

**Expected behavior**
A working VNC session, like yesterday before I upgraded my system to the latest release. 

**Screenshots**

**Client (please complete the following information):**
 - OS: FreeBSD 14.1-RELEASE-p5
 - VNC client: TigerVNC
 - VNC client version: 1.14
 - Client downloaded from: FreeBSD binary repository

**Server (please complete the following information):**
 - OS: Windows 11 Pro
 - VNC server: TightVNC
 - VNC server version: latest
 - Server downloaded from: www.tightvnc.com
 - Server was started using: Windows 11 Pro Run as a Service on Startup

**Additional context**
None.

**Comment by CendioOssman** [comment] 2024-10-28 08:44
My guess would be a duplicate of #1789. Could you check the authentication settings in the client and make sure "Standard VNC" is enabled?

This issue should also be resolved in TigerVNC 1.14.1, but only if the broken settings aren't already saved.

**Comment by t4n1s** [comment] 2024-10-28 15:13
Indeed, it is, thx! =D

**Closed** 2024-10-28 15:48 UTC
