### ISSUE TITLE
Sometimes graphical artifacts are visible with TigerVNC server on Windows when the VNC client is configured to show the remote pointer locally

### ISSUE THREAD

**Issue by achim-s** [TigerVNC/tigervnc#543] opened 2017-11-20 09:37 UTC
How to reproduce:
- Run novnc client and connect to a TigerVNC server running on Windows OS (we tested with W10 and W7).
- Make sure that option 'Local Cursor', located in the 'Advanced' view of the 'Settings' dialog is unchecked for novnc.
- On the remote side, open an application window.
- Drag the window upward and downward using the mouse pointer. Stop the drag operation after few repeats.

Observation: There is a chance that after stopping the drag operation small areas are visible that are not correctly updated. These are following the path of the pointer movement. See the jpg attached (which is a very extreme case).

The TigerVNC server is configured as follows
- Capture Method: 'Poll for changes to the desktop'
- Desktop: While connected 'Disable user interface effects'

The TigerVNC version used for testing is the nightly build from 17th of November 2017.

Observation is the same with TightVNC viewer and option 'Let remote server deal with cursor' enabled: As this is visible with two different clients, we currently think this is a server side issue.

![screenshot](https://user-images.githubusercontent.com/33827166/33011622-ca6101ec-cdde-11e7-9542-6b790f65df1c.jpg)

**Comment by CendioOssman** [comment] 2017-11-21 14:25
I'm afraid I'm unable to reproduce this. Which build of TigerVNC were you using? Could you try the latest nightly?

**Comment by CendioOssman** [comment] 2017-11-21 14:27
Hang on, I got it now. I had to enable some more visual bling in Windows for this to trigger.

**Comment by CendioOssman** [comment] 2017-11-22 14:48
There is something weird going on with copied areas and the mouse cursor overlapping...

What's the reason you have disabled local cursor though? That option will be removed from future versions of noVNC.

**Comment by achim-s** [comment] 2017-11-23 12:16
Hi Pierre

In fact, i was using noVNC with the described pointer configuration just to allow for easy reproduction of the problem: In our product we integrate a commercial, closed source VNC viewer from a small company (called RemoteSpark), which shows the same problem. Some of our customers just prefer the pointer configuration that shows the problem described. Towards our customers we recommend to use TigerVNC as VNC server, so we are interested in having this solved.
Btw, we still plan to offer a bounty for the fix, but there are still some administrative steps required to get this done.

Regards

Achim

**Comment by CendioOssman** [comment] 2017-11-23 12:54
Ah, alright.

I think I have some idea what's going on though so I might have a fix ready this week. So I don't think a bounty won't be necessary. But feel free to give a general donation to the project if you'd like. :)

**Comment by CendioOssman** [comment] 2017-11-24 11:36
Alright, this has been fixed in cf647a33718f5dfffb4f4df3a7ae4235e83a4065.

**Closed by CendioOssman** 2017-11-24 11:36 UTC
Labels: bug

**Comment by achim-s** [comment] 2017-11-24 13:52
Great. I will perform some tests begin of next week.
Once more, thanks for the quick action.

**Comment by achim-s** [comment] 2017-11-28 15:26
We didn't observe this anymore using the TigerVNC nightly that includes the mentioned commit.
Btw ... do you already have any plans for the next official release?

And w.r. to _'But feel free to give a general donation to the project if you'd like. :)'_ ... something will be done about that.

**Comment by CendioOssman** [comment] 2017-11-29 07:51
> Btw ... do you already have any plans for the next official release?

No firm plans, but I'm thinking soon-ish.
