### ISSUE TITLE
DeferUpdate is broken

### ISSUE THREAD

**Issue by vnallamothu** [TigerVNC/tigervnc#443] opened 2017-04-03 21:42 UTC
Since upgrading to Fedora 25 (from fedora 24) in Nov '16, consistently noticed that when using terminal applications lxterminal, gnome-terminal, screen doesn't get refreshed till there is either a keyboard or a mouse input. This is easy to notice if the cursor blinking is turned off and there is no mouse movement. 

Example:
$ ssh some-ssh-server
Password:            <----------- Prompt doesn't appear till some key is pressed (e.g: shift) or mouse movement

I have found similar screen refresh issues with various applications like editing at shell prompt or vi.

These issues were not noticed when tried over ssh or locally.

Found that turning off DeferUpdate resolved the issue. Any value above 0 causes problem.

**Comment by vnallamothu** [comment] 2017-04-03 21:44
Issue seen with tigervnc-1.7.1-1.fc25.x86_64 and earlier rpms on FC25

**Comment by CendioOssman** [comment] 2017-04-04 14:00
What is the client in this case?

**Comment by vnallamothu** [comment] 2017-04-04 20:29
I got same behavior with different clients: RealVNC 6.02 and 5.x, TurboVNC 2.1 and TigerVNC 1.7.1

**Comment by CendioOssman** [comment] 2017-04-05 13:43
I'm afraid I cannot reproduce this issue. I tried i using tigervnc-server-1.7.1-1.fc25.x86_64 and the client was tigervnc-1.7.1-1.fc25.x86_64. I used a Gnome desktop and ran `sleep 2; echo foo` in gnome-terminal with cursor blink disabled. Everything showed up just fine.

How do you start your server? Have you added some extra configuration?

**Comment by CendioOssman** [comment] 2017-04-05 13:46
Also, what is your network infrastructure between the client and the server? Could there be something there that delays packets?

**Comment by vnallamothu** [comment] 2017-04-05 16:13
I am able to repro with "sleep 2; echo foo". 

Issue won't be seen if there is any screen update (e.g: clock). On my desktop, clock updates every 1 minute. I see the output appearing only when the clock is updated. 

(I am using fluxbox and lxterminal on Linux).

Client is on Windows 10 and is on the same LAN as server and there shouldn't be any delay.

C:\Users\vnallamothu> ping vnallamothu-lnx

Pinging vnallamothu-lnx [172.21.33.16] with 32 bytes of data:
Reply from 172.21.33.16: bytes=32 time<1ms TTL=64
Reply from 172.21.33.16: bytes=32 time<1ms TTL=64
Reply from 172.21.33.16: bytes=32 time<1ms TTL=64
Reply from 172.21.33.16: bytes=32 time<1ms TTL=64

Ping statistics for 172.21.33.16:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
vncserver -geometry 1366x768 :3644

vnallamothu-lnx: /home/vnallamothu/.vnc> cat xstartup
#!/bin/sh

## Disable wayland
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export XDG_SESSION_TYPE=x11


export XKL_XMODMAP_DISABLE=1
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey

vncconfig -nowin &
(startfluxbox || blackbox || openbox || xterm ) &

**Comment by CendioOssman** [comment] 2017-04-06 09:17
Some crucial piece is still missing. I used your xstartup script, and connected from Windows, and I'm still not getting this issue.

Any special settings configured for Xvnc?

Have you tried creating a new user and see if the problem remains? It's worthwhile to try this both on the client and server. It could be some configuration affecting this.

**Comment by vnallamothu** [comment] 2017-04-06 19:14
I retried with a new account on the server. This time i am unable to recreate the issue with "sleep 2; echo foo".

But, i can still trigger the issue with ssh client's  password prompt.
Steps i followed:
1. vnc to the server running Xvnc
2. Invoke lxterminal
3. From lxterminal prompt ssh to another server
4. ssh password prompt doesn't appear till i press some key or there is screen update (clock or mouse pointer)

Also tried with telnet and same issue at login prompt but not consistent. 

Once i login to the ssh/telnet server and if i run the "sleep 2; echo" on ssh server, i can see the issue consistently.

It's possible that when i previously tried the "sleep 2; echo", i was logged into a ssh server.

Other clients i have tried and the issue not observed with:
           1. cygwin ssh to vnc server machine and then ssh to another server
           2. SmarTTy ssh to vnc server machine and then do an ssh to another server
           3. SmarTTy ssh to vnc server, invoke lxterminal (smartty has builtin X server)  and then do an ssh to another server

My guess is issue is seen triggered by programs that use termcap

By far ssh reproduces the issue most reliably.

Here is how i start Xvnc through vncserver

$ vncserver -geometry 1366x768 :3646

$ ps aux | grep Xvnc

vnctest    691  0.3  1.4 274932 59796 pts/18   Sl   10:57   0:08 /usr/bin/Xvnc :3646 -auth /home/vnctest/.Xauthority -desktop vnallamothu-lnx:3646 (vnctest)
 -fp catalogue:/etc/X11/fontpath.d -geometry 1366x768 -pn -rfbauth /home/vnctest/.vnc/passwd -rfbport 9546 -rfbwait 30000

If still not reproducible, will try to share screen recording. Anything else i should try ?

**Comment by CendioOssman** [comment] 2017-04-07 08:59
I was actually managed to reproduce it now. And I realised this is TigerVNC 1.7.1 and Xorg 1.19, which isn't really a supported combination. Fedora has tried to patch this, but their patch is broken. So I'm afraid this is a Fedora bug, not a TigerVNC bug.

You should report the bug to them and tell them to look at how 1.19 support has been implemented on `master`. Primarily commit b192107b302098864358cd54b6323129c23e271e.

This will also be resolved in 1.8.0, which will hopefully be out soon.

**Closed by CendioOssman** 2017-04-07 08:59 UTC
