### ISSUE TITLE
VNC Viewer does not full-screen to all monitors after reopening from minimized

### ISSUE THREAD

**Issue by jakecrowley** [TigerVNC/tigervnc#1474] opened 2022-06-01 14:45 UTC
**Describe the bug**
After minimizing TigerVNC Viewer with F8 -> Minimize, after reopening the viewer by clicking on it in the taskbar, it will only reopen on the current monitor, even when "Use all monitors" is enabled in Connection Options -> Screen.

**To Reproduce**
1. Make sure TigerVNC Viewer is fullscreened and "Use all monitors" is enabled.
2. Minimize the viewer with F8 -> Minimize
3. Reopen TigerVNC from minimized
4. It only full-screens on the current monitor.

**Expected behavior**
TigerVNC reopens and full-screens on all monitors.

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNC
 - VNC client version: v1.12.0 64-bit
 - Client downloaded from: https://sourceforge.net/projects/tigervnc/files/stable/1.12.0/vncviewer64-1.12.0.exe/download

**Comment by CendioOssman** [comment] 2022-06-02 14:25
We have #283 previously filed. On that bug, maximize before full screen was needed to trigger the problem. Is it the same in your case?

**Comment by jakecrowley** [comment] 2022-06-02 18:15
> On that bug, maximize before full screen was needed to trigger the problem. Is it the same in your case?

Yes, it does need to be maximized first. i missed that since I never tried otherwise.

**Comment by CendioOssman** [comment] 2022-06-13 05:52
Thanks for testing!

I'll close this as a duplicate of #283 then, so we don't have the discussion spread out over multiple issues.

**Closed by CendioOssman** 2022-06-13 05:52 UTC
