### ISSUE TITLE
Delay between connection init and password prompt popup using VNCViewer 1.9.80 nightly

### ISSUE THREAD

**Issue by mr-kobalt** [TigerVNC/tigervnc#864] opened 2019-08-27 10:21 UTC
Hello,

I have some issues with nightly build of the Viewer for Windows, wonder if you could help investigate it further.

There is a approximately 2 minute delay between the moment I initialize the connection and password prompt popup. Please, find logs below. Besides that delay, connection established normally. My best guess is that the issue is related with that string in Client logs: ` TLS:         Could not load system certificate trust store` (hence with the commit c04f756?)

I've tried `.jar` client, as well as the old `1.9.0` release version, and both of them do not have this issue. Any thoughts what else I could try to do?

_Off topic: also, I could confirm that the issue #20 is resolved and Unicode string transfer through clipboard works flawlessly (main reason I'm trying nightly builds)_

**Client log:**

```
Tue Aug 27 11:39:22 2019
 DecodeManager: Detected 4 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 TcpSocket:   Connecting to my.domain.name [1.2.3.4] port 5910
 CConn:       Connected to host my.domain.name port 5910
 CConnection: reading protocol version
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: processing security types message
 CConnection: Server offers security type VeNCrypt(19)
 CConnection: Choosing security type VeNCrypt(19)
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CVeNCrypt:   Server offers security type X509Vnc (261)
 CVeNCrypt:   Choosing security type X509Vnc (261)
 CConnection: processing security message

Tue Aug 27 11:41:21 2019
 TLS:         Could not load system certificate trust store
 TLS:         X509 session has been set
 CConnection: processing security message
 CConnection: processing security message
 TLS:         TLS handshake completed with
              (TLS1.2)-(ECDHE-RSA-SECP256R1)-(AES-256-GCM)

Tue Aug 27 11:41:36 2019
 CConnection: processing security result message
 CConnection: processing security result message
 CConnection: Authentication success!
 CConnection: reading server initialisation
 CConnection: initialisation done
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 Viewport:    Got server LED state: 0x00000002
 CConnection: Enabling continuous updates
```

**Server log:**

```
<..>
Tue Aug 27 11:39:24 2019
 Connections: accepted: 172.16.1.1::56490
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VeNCrypt(19)
 SVeNCrypt:   Client requests security type X509Vnc (261)

Tue Aug 27 11:41:38 2019
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888

Tue Aug 27 11:41:46 2019
 VNCSConnST:  closing 172.16.1.1::56490: Clean disconnection
 EncodeManager: Framebuffer updates: 46
 EncodeManager:   Tight:
 EncodeManager:     Solid: 42 rects, 240.517 kpixels
 EncodeManager:            672 B (1:1432.4 ratio)
 EncodeManager:     Bitmap RLE: 4 rects, 6.012 kpixels
 EncodeManager:                 141 B (1:170.894 ratio)
 EncodeManager:     Indexed RLE: 22 rects, 54.712 kpixels
 EncodeManager:                  5.68164 KiB (1:37.6611 ratio)
 EncodeManager:   Tight (JPEG):
 EncodeManager:     Full Colour: 106 rects, 1.14621 Mpixels
 EncodeManager:                  723.528 KiB (1:6.18999 ratio)
 EncodeManager:   Total: 174 rects, 1.44745 Mpixels
 EncodeManager:          730.004 KiB (1:7.74811 ratio)
 TLS:         TLS session wasn't terminated gracefully
 Connections: closed: 172.16.1.1::56490
 ComparingUpdateTracker: 7.86432 Mpixels in / 86.016 kpixels out
 ComparingUpdateTracker: (1:91.4286 ratio)
Предупреждение менеджера окон: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x30001f2 (Бухга)
Предупреждение менеджера окон: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Предупреждение менеджера окон: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x30001f2 (Бухга)
Предупреждение менеджера окон: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
<..>
```

_* `Предупреждение менеджера окон` means `Window manager warning`_
_** `Бухга` makes no sense in Russian_

**Client:**
 - OS: Windows 10 Enterprise 1809 (OS Build 17763.678)
 - VNC client: TigerVNC 1.9.80 x86_64 - nightly build Aug 26 2019
 - Client downloaded from: http://tigervnc.bphinz.com/nightly/
 - Client config: 
```
ServerName=my.domain.name:5910
X509CA=E:\\path\\to\\cert\\cert.crt
X509CRL=
SecurityTypes=X509Vnc
DotWhenNoCursor=0
AutoSelect=1
FullColor=1
LowColorLevel=2
PreferredEncoding=Tight
CustomCompressLevel=0
CompressLevel=2
NoJPEG=0
QualityLevel=8
FullScreen=0
FullScreenAllMonitors=0
DesktopSize=1024x768
geometry=
RemoteResize=1
ViewOnly=0
Shared=1
AcceptClipboard=1
SendClipboard=1
MenuKey=F8
FullscreenSystemKeys=1
AlertOnFatalError=1
```

**Server:**
 - OS: CentOS Linux release 7.6.1810 (Core)
 - VNC server: TigerVNC 1.9.80 x86_64 - nightly build Aug 26 2019
 - Server downloaded from: http://tigervnc.bphinz.com/nightly/
 - Server was started using: as a **systemd** service `vncserver@:10.service` with `ExecStart=/usr/sbin/runuser -l usr1cv8 -c /usr/bin/vncserver %i`

**Comment by CendioOssman** [comment] 2019-10-04 11:21
Hmm... Annoying that it is on Windows. If it was Linux we could do some more tracing.

@bphinz, what version of GnuTLS are you using for the Windows builds? Could you try an upgrade?

**Comment by bphinz** [comment] 2019-10-09 11:28
> @bphinz <https://github.com/bphinz>, what version of GnuTLS are you using
for the Windows builds? Could you try an upgrade?

I can't access the build servers from my work.  I'll check later tonight
and get back to you.

**Comment by mr-kobalt** [comment] 2019-10-09 15:21
I just tried to use latest nightly build of the viewer on the different machine with `Windows 10 Pro 1903 10.0.18990.1` (Insider Preview) on it and there was no delay at all. I am baffled. So I assume that problem is in my particular software configuration. Sorry for not testing the problem thoroughly as needed.

By the end of the week I would have a chance to test viewer on yet another windows machine, and then I'll get back to you with an update.

**Comment by bphinz** [comment] 2019-10-10 00:04
3.5.19, which is the latest release in the 3.5.x series.  I will try
upgrading to the latest 3.6

**Comment by bphinz** [comment] 2019-12-24 17:09
The windows binaries are now being built against gnutls 3.6.11.1

**Comment by mr-kobalt** [comment] 2019-12-25 10:39
Thank you, @bphinz , but latest binaries still does not work for one of my machines. I pretty sure that this is the result of some misconfiguration from my part or buggy third party software behavior. Anyway, I don't know how to debug this problem, so any advice will be much appreciated, otherwise I suggest we close the issue.

**Comment by CendioOssman** [comment] 2019-12-30 10:15
Hmm... I cannot reproduce this issue here. It connects without any delay.

What happens if you remove the CA in the client configuration? It will probably complain about an unknown issuer, but it will be interesting to see if the delay is still present.

**Comment by kflu** [comment] 2021-07-22 07:51
OK, major discovery to fix (workaround) this - I found that if I use a larger server port, the delay is gone:

    vncserver -rfbport 15901 :1

So probably something funky about my server setup (which I don't control). As I checked though, no other processes is using/listening on port 5901.

**Comment by CendioOssman** [comment] 2021-07-23 08:36
The original reporter seems to be long gone, so I'm going to close this issue.

@kflu, sounds like there is something on your network messing with your connection. Unfortunately that is not something we can really help you out with. You'll have to pinpoint what step is causing the issue and get this resolved there. I would guess some firewall trying to do something special since it is VNC traffic.

**Closed by CendioOssman** 2021-07-23 08:36 UTC
Labels: bug

**Comment by dagelf** [comment] 2023-02-28 11:18
`tigervnc-standalone-server/bionic,now 1.7.0+dfsg-8ubuntu2 amd64`

Same issue, connecting from Linux, OSX and Windows. So must be something on the server side.

**Comment by lnxusr88** [comment] 2023-05-17 19:49
I noticed the same problem (which recently appeared). In my case, the initial connection attempt was made using IPv6, it timed out, and then connected with IPv4. I edited /etc/gai.conf to prefer IPv4 on the client host, and that solved the problem.
