### ISSUE TITLE
unable to open the service: The specified services does not exist as an installed service. (1060)

### ISSUE THREAD

**Issue by adamreed90** [TigerVNC/tigervnc#334] opened 2016-07-28 17:05 UTC
Running Windows 10, Installed 1.7beta, did not create a service. 

Attempted: 

> C:\WINDOWS\system32>cd C:\Program Files\TigerVNC
> 
> C:\Program Files\TigerVNC>winvnc4.exe
> 
> C:\Program Files\TigerVNC>winvnc4.exe -unregister
> 
> C:\Program Files\TigerVNC>winvnc4.exe -noconsole -start
> 
> C:\Program Files\TigerVNC>winvnc4.exe -register
> 
> C:\Program Files\TigerVNC>winvnc4.exe -noconsole -start
> 
> C:\Program Files\TigerVNC>winvnc4.exe -noconsole -start
> 
> C:\Program Files\TigerVNC>winvnc4.exe -noconsole -start

Got the same error every time.

**Comment by mihailim** [comment] 2016-08-09 13:12
This is caused by commit ed92079eb6a7ee7a473cc6b17b10578e10426c88 which tries to remove obsolete service names but doesn't wrap the remove invocations in a try-catch stanza. If the old names do **not** exist, `rfb::win32::unregisterService` will throw an exception which causes the abort.

Reverting the commit fixes the error. I suppose a try-catch around each `rfb::win32::unregisterService` invocation would also work around it, but I didn't try.

**Comment by thelonelyprogrammer** [comment] 2016-08-17 17:26
I ran into the same issue, the service is not created.

**Comment by CendioOssman** [comment] 2016-08-18 14:50
Oops. Sorry about that. Fixed in c7860c2 (and 4830bc9).

**Closed by CendioOssman** 2016-08-18 14:50 UTC
Labels: bug
