### ISSUE TITLE
[Bug] tigervnc with 10-vnc.conf causes Xorg Segmentation fault

### ISSUE THREAD

**Issue by syryyndypyty** [TigerVNC/tigervnc#1572] opened 2023-01-01 19:41 UTC
Tested with latest build for Arch Linux:
https://aur.archlinux.org/packages/tigervnc-git

1. Create the file `/etc/X11/xorg.conf.d/10-vnc.conf`:
```
Section "Module"
Load "vnc"
EndSection

Section "Screen"
Identifier "Screen0"
Option "UserPasswdVerifier" "VncAuth"
Option "PasswordFile" "/root/.vnc/passwd"
EndSection
```

2. Install:
```
$ pamac build tigervnc-git
```

3. After reboot, the system does not load login manager. Here's the Xorg.0.log:
```
[    29.525] (--) Log file renamed from "/var/log/Xorg.pid-1185.log" to "/var/log/Xorg.0.log"
[    29.526] 
X.Org X Server 1.21.1.6
X Protocol Version 11, Revision 0
[    29.526] Current Operating System: Linux arch 6.1.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:55 +0000 x86_64
[    29.526] Kernel command line: ...
[    29.526]  
[    29.526] Current version of pixman: 0.42.2
[    29.526] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[    29.526] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    29.526] (==) Log file: "/var/log/Xorg.0.log", Time: Sun Jan  1 11:29:26 2023
[    29.526] (==) Using config directory: "/etc/X11/xorg.conf.d"
[    29.526] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    29.526] (==) No Layout section.  Using the first Screen section.
[    29.526] (**) |-->Screen "Screen0" (0)
[    29.526] (**) |   |-->Monitor "<default monitor>"
[    29.526] (==) No monitor specified for screen "Screen0".
	Using a default monitor configuration.
[    29.526] (==) Automatically adding devices
[    29.526] (==) Automatically enabling devices
[    29.526] (==) Automatically adding GPU devices
[    29.526] (==) Automatically binding GPU devices
[    29.526] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    29.526] (WW) The directory "/usr/share/fonts/misc" does not exist.
[    29.526] 	Entry deleted from font path.
[    29.526] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/TTF".
[    29.526] 	Entry deleted from font path.
[    29.526] 	(Run 'mkfontdir' on "/usr/share/fonts/TTF").
[    29.526] (WW) The directory "/usr/share/fonts/OTF" does not exist.
[    29.526] 	Entry deleted from font path.
[    29.526] (WW) The directory "/usr/share/fonts/Type1" does not exist.
[    29.526] 	Entry deleted from font path.
[    29.526] (WW) The directory "/usr/share/fonts/100dpi" does not exist.
[    29.526] 	Entry deleted from font path.
[    29.526] (WW) The directory "/usr/share/fonts/75dpi" does not exist.
[    29.526] 	Entry deleted from font path.
[    29.526] (==) FontPath set to:
	
[    29.526] (==) ModulePath set to "/usr/lib/xorg/modules"
[    29.526] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[    29.526] (II) Module ABI versions:
[    29.526] 	X.Org ANSI C Emulation: 0.4
[    29.526] 	X.Org Video Driver: 25.2
[    29.526] 	X.Org XInput driver : 24.4
[    29.526] 	X.Org Server Extension : 10.0
[    29.527] (++) using VT number 1

[    29.527] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[    29.527] (II) xfree86: Adding drm device (/dev/dri/card0)
[    29.527] (II) Platform probe for /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0
[    29.529] (**) OutputClass "nvidia" ModulePath extended to "/usr/lib/nvidia/xorg,/usr/lib/xorg/modules,/usr/lib/xorg/modules"
[    29.530] (--) PCI:*(1@0:0:0) ...
[    29.531] (WW) Open ACPI failed (/var/run/acpid.socket) (No such file or directory)
[    29.531] (II) "glx" will be loaded by default.
[    29.531] (II) LoadModule: "vnc"
[    29.531] (II) Loading /usr/lib/xorg/modules/extensions/libvnc.so
[    29.551] (II) Module vnc: vendor="TigerVNC Project"
[    29.551] 	compiled for 1.20.9, module version = 1.0.0
[    29.551] 	Module class: X.Org Server Extension
[    29.551] 	ABI class: X.Org Server Extension, version 10.0
[    29.551] (II) LoadModule: "glx"
[    29.551] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    29.552] (II) Module glx: vendor="X.Org Foundation"
[    29.552] 	compiled for 1.21.1.6, module version = 1.0.0
[    29.552] 	ABI class: X.Org Server Extension, version 10.0
[    29.552] (II) Applying OutputClass "nvidia" to /dev/dri/card0
[    29.552] 	loading driver: nvidia
[    29.552] (==) Matched nvidia as autoconfigured driver 0
[    29.552] (==) Matched nouveau as autoconfigured driver 1
[    29.552] (==) Matched nv as autoconfigured driver 2
[    29.552] (==) Matched modesetting as autoconfigured driver 3
[    29.552] (==) Matched fbdev as autoconfigured driver 4
[    29.552] (==) Matched vesa as autoconfigured driver 5
[    29.552] (==) Assigned the driver to the xf86ConfigLayout
[    29.552] (II) LoadModule: "nvidia"
[    29.552] (II) Loading /usr/lib/xorg/modules/drivers/nvidia_drv.so
[    29.553] (II) Module nvidia: vendor="NVIDIA Corporation"
[    29.553] 	compiled for 1.6.99.901, module version = 1.0.0
[    29.553] 	Module class: X.Org Video Driver
[    29.553] (II) LoadModule: "nouveau"
[    29.553] (WW) Warning, couldn't open module nouveau
[    29.553] (EE) Failed to load module "nouveau" (module does not exist, 0)
[    29.553] (II) LoadModule: "nv"
[    29.553] (WW) Warning, couldn't open module nv
[    29.553] (EE) Failed to load module "nv" (module does not exist, 0)
[    29.553] (II) LoadModule: "modesetting"
[    29.553] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[    29.554] (II) Module modesetting: vendor="X.Org Foundation"
[    29.554] 	compiled for 1.21.1.6, module version = 1.21.1
[    29.554] 	Module class: X.Org Video Driver
[    29.554] 	ABI class: X.Org Video Driver, version 25.2
[    29.554] (II) LoadModule: "fbdev"
[    29.554] (WW) Warning, couldn't open module fbdev
[    29.554] (EE) Failed to load module "fbdev" (module does not exist, 0)
[    29.554] (II) LoadModule: "vesa"
[    29.554] (WW) Warning, couldn't open module vesa
[    29.554] (EE) Failed to load module "vesa" (module does not exist, 0)
[    29.554] (II) NVIDIA dlloader X Driver  525.60.11  Wed Nov 23 22:56:57 UTC 2022
[    29.554] (II) NVIDIA Unified Driver for all Supported NVIDIA GPUs
[    29.554] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[    29.554] (II) Loading sub module "fb"
[    29.554] (II) LoadModule: "fb"
[    29.554] (II) Module "fb" already built-in
[    29.554] (II) Loading sub module "wfb"
[    29.554] (II) LoadModule: "wfb"
[    29.554] (II) Loading /usr/lib/xorg/modules/libwfb.so
[    29.555] (II) Module wfb: vendor="X.Org Foundation"
[    29.555] 	compiled for 1.21.1.6, module version = 1.0.0
[    29.555] 	ABI class: X.Org ANSI C Emulation, version 0.4
[    29.555] (II) Loading sub module "ramdac"
[    29.555] (II) LoadModule: "ramdac"
[    29.555] (II) Module "ramdac" already built-in
[    29.555] (WW) Falling back to old probe method for modesetting
[    29.555] (II) NVIDIA(0): Creating default Display subsection in Screen section
	"Screen0" for depth/fbbpp 24/32
[    29.555] (==) NVIDIA(0): Depth 24, (==) framebuffer bpp 32
[    29.555] (==) NVIDIA(0): RGB weight 888
[    29.555] (==) NVIDIA(0): Default visual is TrueColor
[    29.555] (==) NVIDIA(0): Using gamma correction (1.0, 1.0, 1.0)
[    29.555] (II) Applying OutputClass "nvidia" options to /dev/dri/card0
[    29.555] (**) NVIDIA(0): Option "AllowEmptyInitialConfiguration"
[    29.555] (**) NVIDIA(0): Enabling 2D acceleration
[    29.555] (II) Loading sub module "glxserver_nvidia"
[    29.555] (II) LoadModule: "glxserver_nvidia"
[    29.555] (II) Loading /usr/lib/nvidia/xorg/libglxserver_nvidia.so
[    29.568] (II) Module glxserver_nvidia: vendor="NVIDIA Corporation"
[    29.568] 	compiled for 1.6.99.901, module version = 1.0.0
[    29.568] 	Module class: X.Org Server Extension
[    29.569] (II) NVIDIA GLX Module  525.60.11  Wed Nov 23 22:51:25 UTC 2022
[    29.569] (II) NVIDIA: The X server supports PRIME Render Offload.
[    29.825] (--) NVIDIA(0): Valid display device(s) on GPU-0 at PCI:1:0:0
[    29.825] (--) NVIDIA(0):     DFP-0
[    29.825] (--) NVIDIA(0):     DFP-1 (boot)
[    29.825] (--) NVIDIA(0):     DFP-2
[    29.825] (--) NVIDIA(0):     DFP-3
[    29.825] (--) NVIDIA(0):     DFP-4
[    29.825] (--) NVIDIA(0):     DFP-5
[    29.826] (II) NVIDIA(0): NVIDIA GPU NVIDIA GeForce GTX 1080 (GP104-B) at PCI:1:0:0
[    29.826] (II) NVIDIA(0):     (GPU-0)
[    29.826] (--) NVIDIA(0): Memory: 8388608 kBytes
[    29.826] (--) NVIDIA(0): VideoBIOS: 86.04.56.00.3c
[    29.826] (II) NVIDIA(0): Detected PCI Express Link width: 16X
[    29.826] (--) NVIDIA(GPU-0): DFP-0: disconnected
[    29.826] (--) NVIDIA(GPU-0): DFP-0: Internal TMDS
[    29.826] (--) NVIDIA(GPU-0): DFP-0: 165.0 MHz maximum pixel clock
[    29.826] (--) NVIDIA(GPU-0): 
[    29.826] (--) NVIDIA(GPU-0): Chimei innolux corp. (DFP-1): connected
[    29.826] (--) NVIDIA(GPU-0): Chimei innolux corp. (DFP-1): Internal DisplayPort
[    29.826] (--) NVIDIA(GPU-0): Chimei innolux corp. (DFP-1): 1440.0 MHz maximum pixel clock
[    29.826] (--) NVIDIA(GPU-0): 
[    29.826] (--) NVIDIA(GPU-0): DFP-2: disconnected
[    29.826] (--) NVIDIA(GPU-0): DFP-2: Internal DisplayPort
[    29.826] (--) NVIDIA(GPU-0): DFP-2: 1440.0 MHz maximum pixel clock
[    29.826] (--) NVIDIA(GPU-0): 
[    29.826] (--) NVIDIA(GPU-0): DFP-3: disconnected
[    29.826] (--) NVIDIA(GPU-0): DFP-3: Internal TMDS
[    29.826] (--) NVIDIA(GPU-0): DFP-3: 165.0 MHz maximum pixel clock
[    29.826] (--) NVIDIA(GPU-0): 
[    29.826] (--) NVIDIA(GPU-0): DFP-4: disconnected
[    29.826] (--) NVIDIA(GPU-0): DFP-4: Internal DisplayPort
[    29.826] (--) NVIDIA(GPU-0): DFP-4: 1440.0 MHz maximum pixel clock
[    29.826] (--) NVIDIA(GPU-0): 
[    29.826] (--) NVIDIA(GPU-0): DFP-5: disconnected
[    29.826] (--) NVIDIA(GPU-0): DFP-5: Internal TMDS
[    29.826] (--) NVIDIA(GPU-0): DFP-5: 165.0 MHz maximum pixel clock
[    29.826] (--) NVIDIA(GPU-0): 
[    29.828] (==) NVIDIA(0): 
[    29.828] (==) NVIDIA(0): No modes were requested; the default mode "nvidia-auto-select"
[    29.828] (==) NVIDIA(0):     will be used as the requested mode.
[    29.828] (==) NVIDIA(0): 
[    29.828] (II) NVIDIA(0): Validated MetaModes:
[    29.828] (II) NVIDIA(0):     "DFP-1:nvidia-auto-select"
[    29.828] (II) NVIDIA(0): Virtual screen size determined to be 1920 x 1080
[    29.831] (--) NVIDIA(0): DPI set to (128, 130); computed from "UseEdidDpi" X config
[    29.831] (--) NVIDIA(0):     option
[    29.831] (II) UnloadModule: "modesetting"
[    29.831] (II) Unloading modesetting
[    29.831] (II) NVIDIA: Reserving 24576.00 MB of virtual memory for indirect memory
[    29.831] (II) NVIDIA:     access.
[    29.864] (II) NVIDIA(0): ACPI: failed to connect to the ACPI event daemon; the daemon
[    29.864] (II) NVIDIA(0):     may not be running or the "AcpidSocketPath" X
[    29.864] (II) NVIDIA(0):     configuration option may not be set correctly.  When the
[    29.864] (II) NVIDIA(0):     ACPI event daemon is available, the NVIDIA X driver will
[    29.864] (II) NVIDIA(0):     try to use it to receive ACPI event notifications.  For
[    29.864] (II) NVIDIA(0):     details, please see the "ConnectToAcpid" and
[    29.864] (II) NVIDIA(0):     "AcpidSocketPath" X configuration options in Appendix B: X
[    29.864] (II) NVIDIA(0):     Config Options in the README.
[    29.881] (II) NVIDIA(0): Setting mode "DFP-1:nvidia-auto-select"
[    30.766] (==) NVIDIA(0): Disabling shared memory pixmaps
[    30.766] (==) NVIDIA(0): Backing store enabled
[    30.766] (==) NVIDIA(0): Silken mouse enabled
[    30.767] (==) NVIDIA(0): DPMS enabled
[    30.767] (WW) NVIDIA(0): Option "UserPasswdVerifier" is not used
[    30.767] (WW) NVIDIA(0): Option "PasswordFile" is not used
[    30.767] (II) Loading sub module "dri2"
[    30.767] (II) LoadModule: "dri2"
[    30.767] (II) Module "dri2" already built-in
[    30.767] (II) NVIDIA(0): [DRI2] Setup complete
[    30.767] (II) NVIDIA(0): [DRI2]   VDPAU driver: nvidia
[    30.767] (II) Initializing extension Generic Event Extension
[    30.767] (II) Initializing extension SHAPE
[    30.767] (II) Initializing extension MIT-SHM
[    30.767] (II) Initializing extension XInputExtension
[    30.767] (II) Initializing extension XTEST
[    30.767] (II) Initializing extension BIG-REQUESTS
[    30.768] (II) Initializing extension SYNC
[    30.768] (II) Initializing extension XKEYBOARD
[    30.768] (II) Initializing extension XC-MISC
[    30.768] (II) Initializing extension SECURITY
[    30.768] (II) Initializing extension XFIXES
[    30.768] (II) Initializing extension RENDER
[    30.768] (II) Initializing extension RANDR
[    30.768] (II) Initializing extension COMPOSITE
[    30.768] (II) Initializing extension DAMAGE
[    30.768] (II) Initializing extension MIT-SCREEN-SAVER
[    30.768] (II) Initializing extension DOUBLE-BUFFER
[    30.769] (II) Initializing extension RECORD
[    30.769] (II) Initializing extension DPMS
[    30.769] (II) Initializing extension Present
[    30.769] (II) Initializing extension DRI3
[    30.769] (II) Initializing extension X-Resource
[    30.769] (II) Initializing extension XVideo
[    30.769] (II) Initializing extension XVideo-MotionCompensation
[    30.769] (II) Initializing extension GLX
[    30.769] (II) Initializing extension GLX
[    30.769] (II) Indirect GLX disabled.
[    30.769] (II) GLX: Another vendor is already registered for screen 0
[    30.769] (II) Initializing extension XFree86-VidModeExtension
[    30.769] (II) Initializing extension XFree86-DGA
[    30.769] (II) Initializing extension XFree86-DRI
[    30.769] (II) Initializing extension DRI2
[    30.769] (II) Initializing extension VNC
[    30.769] (EE) 
[    30.769] (EE) Backtrace:
[    30.770] (EE) 0: /usr/lib/Xorg (WriteToClient+0x3ed) [0x562754a4153d]
[    30.770] (EE) 1: /usr/lib/libc.so.6 (__sigaction+0x50) [0x7fd09d050a00]
[    30.770] (EE) 2: /usr/lib/Xorg (xf86OptionValue+0xb) [0x562754a5573b]
[    30.771] (EE) 3: /usr/lib/xorg/modules/extensions/libvnc.so (_ZN3rfb14JpegCompressor10writeBytesEPKvi+0x2a99) [0x7fd09c691d71]
[    30.771] (EE) 4: /usr/lib/Xorg (InitExtensions+0x89) [0x562754934da9]
[    30.771] (EE) 5: /usr/lib/Xorg (SProcXkbDispatch+0x18b3) [0x562754927eda]
[    30.772] (EE) 6: /usr/lib/libc.so.6 (__libc_init_first+0x90) [0x7fd09d03b290]
[    30.772] (EE) 7: /usr/lib/libc.so.6 (__libc_start_main+0x8a) [0x7fd09d03b34a]
[    30.772] (EE) 8: /usr/lib/Xorg (_start+0x25) [0x5627549292d5]
[    30.772] (EE) 
[    30.772] (EE) Segmentation fault at address 0x100000011
[    30.772] (EE) 
Fatal server error:
[    30.772] (EE) Caught signal 11 (Segmentation fault). Server aborting
[    30.772] (EE) 
[    30.772] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[    30.772] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
[    30.772] (EE) 
[    31.640] (EE) Server terminated with error (1). Closing log file.
```

4. Removing the file or uninstalling tigervnc-git restores the system as before.

**Comment by bphinz** [comment] 2023-01-01 19:52
Duplicate of #1536.  The short answer is that your Xorg and libvnc.so were not built from the same sources:

X.Org X Server 1.21.1.6
X Protocol Version 11, Revision 0
...
[    29.531] (II) Loading /usr/lib/xorg/modules/extensions/libvnc.so
[    29.551] (II) Module vnc: vendor="TigerVNC Project"
[    29.551] 	compiled for 1.20.9, module version = 1.0.0

**Closed by bphinz** 2023-01-01 19:52 UTC
