### ISSUE TITLE
Cannot type any key using VNCViewer for Mac connected with VNCServer for Linux

### ISSUE THREAD

**Issue by s-masashi** [TigerVNC/tigervnc#388] opened 2016-12-08 00:25 UTC
Hi,

When I connect to Linux VNCServer (TigerVNC 1.7 on Ubuntu 14 or so) from VNCViewer (TigerVNC 1.7 also) for Mac (macOS 10.12.1), I cannot type any key. Although I can move, click, and drag mouse pointer.

In short,
VNCServer on Linux + VNCViewer on Mac => PROBLEM (No keyboard input)
VNCServer on Linux + VNCViewer on Windows => OK, no problem
VNCServer on Linux + VNCViewer on Linux => OK, no problem

Does anybody have the same problem? Please advice me.
I have this problem from TigerVNC 1.5 or former version

**Comment by CendioOssman** [comment] 2016-12-08 14:04
I'm not seeing any problems here. Could you try on a different Mac?

Could you also produce a [debug log](https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs)?

**Comment by s-masashi** [comment] 2016-12-12 03:42
Thanks for your reply Pierre.
I tried debug log and found the following lines;

```
 CConn:       Using Tight encoding
 Viewport:    Unexpected release of key code 36

Mon Dec 12 11:52:28 2016
 CConn:       Enabling continuous updates

Mon Dec 12 11:52:31 2016
 Viewport:    No symbol for key code 0x00 (in the current state)
 Viewport:    Unexpected release of key code 0
```
You can also find entire log. It's those I connected some VNC server on Linux (with TigerVNC 1.7) and tried a few key strokes. (As I wrote, there was no response on the screen.) 
[log.zip](https://github.com/TigerVNC/tigervnc/files/645068/log.zip)

Any advice for this symptom? Please.

And, would you please tell me how can I build Mac version TigerVNC Viewer from source code?

**Comment by s-masashi** [comment] 2016-12-12 04:01
Hi Pierre, I could solve this problem.
By changing keyboard type from "Hiragana (a Japanese keyboard input method)" to "U. S. International - PC", I could apply keystrokes to VNC Server on Linux.

Thanks.

**Comment by CendioOssman** [comment] 2016-12-12 11:55
That is strange. You should also have Romaji as a keyboard option when you configure Japanese layout, and TigerVNC should switch to that automatically.

**Comment by turtleizzy** [comment] 2017-01-25 12:29
Same problem encountered except that the IME I was using was 'Alphabet' of Google Japanese IME instead of 'Hiragana' mentioned above. Switching IME to 'US International' solved this flawlessly.

**Comment by mtake** [comment] 2019-03-29 02:27
I had the same problem with 'Alphanumeric' of Google Japanese IME, and solved with the standard 'ABC' input source.

**Comment by CendioOssman** [comment] 2019-04-03 14:16
For those of you using "Hiragana", could you show me a screenshot of your input settings? I'm unable to configure it in a way that breaks.

As for Google's "Alphanumeric", it just seems to be broken. It seems to claim to be a "Roman" layout, but refuses to actually provide layout data. At best we might be able to filter it out and refuse to use it so that the system falls back to an actual roman layout.

I don't quite understand the point of the Alphanumeric layout though. Isn't it just the same as the standard ABC but with more complexity?

**Comment by CendioOssman** [comment] 2019-04-04 08:56
I was able to provide some better robustness against Google's "Alphanumeric" in 005db3528df041d1bbd69a07fa41ef7ea4404c19. However there is still some brokenness as that IME doesn't set an explicit physical layout, but rather just keeps whatever was set before.

That doesn't fix anything with Hiragana though, so those of you having issues there, please provide a screen shot of your input settings. Until then I'm closing this issue.

**Closed by CendioOssman** 2019-04-04 08:56 UTC

**Comment by episodeyang** [comment] 2019-09-16 12:11
@s-masashi The funny thing is that it is *exactly* the same issue for me. I had romanji keyboard activated.

**Comment by episodeyang** [comment] 2019-09-16 12:14
To help provide a bit of context: It makes sense for TigerVNC to not function when the IME is non-US. Users usually have both English and CKJ input method, so they can switch back.

The confusing bit for me was that I didn't really know which IME was active at the time, and the other VNC client types with no problem. Had to google "tigervnc not sending key strokes" and this is the first hit.

So the issue is user don't know what is causing the keystrokes to not propagate through. I only googled after the problem is still there after a restart.

**Comment by episodeyang** [comment] 2019-09-16 12:16
To reproduce the issue: add japanese input method, activate either Romanji or Hiragana. Type in Tiger and nothing would happen except modifiers. 

instead of fixing the keyboard handling, having a pop up to notify the user of the problem might be a good alternative.
