### ISSUE TITLE
Server becomes unresponsive with large clipboard update, even though the update is ignored

### ISSUE THREAD

**Issue by dcommander** [TigerVNC/tigervnc#1482] opened 2022-06-16 17:01 UTC
**Describe the bug**
When using the TigerVNC Server and Viewer, attempting to copy/paste a very large (80 MB) block of text from client to server renders the server unresponsive [1], even though the clipboard update is ignored by the server.

[1] very very slow to respond, but you can still control it if you are willing to wait a while

**To Reproduce**
1. Create a very large text file on the client, e.g. by running
```
for i in {1..1000000}; do echo "01234567890123456789012345678901234567890123456789012345678901234567890123456789" >>frickin_huge_clipboard.txt; done
```
2. Open the large text file in a text editor on the client.  (I use BBEdit, but not sure if that matters.)
3. Select all.
4. Copy.
5. Switch to the TigerVNC Viewer window.
6. Open a text editor on the server.  (I use GEdit and the MATE window manager, but not sure if that matters.)
7. Try to paste the text into the server-side text editor using the middle mouse button.

The server will become unresponsive until the viewer is disconnected.  This will remain true even if:
- The clipboard contents change on the client, regardless of the size of the new clipboard contents.
- The clipboard contents change on the server, regardless of the size of the new clipboard contents.
- The text editor is killed on the server.

**Expected behavior**
The server should remain responsive after the overly large clipboard update is ignored.  The server behaves correctly with VNC viewers that do not support the extended clipboard extension.  The incorrect behavior is observed only with the extended clipboard extension.  When the server becomes unresponsive, it is unresponsive for all connected viewers, including those that do not support the extended clipboard extension, but disconnecting the viewer from which the huge clipboard update originated instantly eliminates the problem and makes the server responsive for other viewers.

**Client (please complete the following information):**
 - OS: macOS Big Sur
 - VNC client: TigerVNC
 - VNC client version: 1.12.0
 - Client downloaded from: SourceForge

**Server (please complete the following information):**
 - OS: CentOS 7.9
 - VNC server: TigerVNC
 - VNC server version: 1.12.0
 - Server downloaded from: SourceForge
 - Server was started using: systemd

**Comment by CendioOssman** [comment] 2022-06-20 07:14
I tried to replicate the issue here, and I'm afraid I'm only getting a very brief hiccup. What's the bandwidth between your client and server? Could that be the source of the delay?

I would have expected #1029 to keep other clients running. So that's the most surprising part.

**Comment by dcommander** [comment] 2022-06-20 14:20
This occurred on a gigabit LAN, so the network was not the source of the delay. Also, the fact that the issue did not occur when the extended clipboard extension was disabled in the viewer suggests that the issue may be in the viewer rather than in the server.

**Comment by dcommander** [comment] 2022-06-21 16:31
I'll do some more testing and get back to you.

**Comment by dcommander** [comment] 2022-06-21 22:20
Further testing seems to indicate that a ridiculously huge clipboard update is not required in order to trigger the issue.  A 1 MB update containing random data will suffice:
```
for i in {1..13000}; do
	LINE=""
	for j in {1..80}; do
		LINE=${LINE}$(($RANDOM % 10))
	done
	echo $LINE
done
```
The delay between server responses is much less in this case than it was with the 81 MB clipboard update, but the connection is still effectively unusable.

**Comment by CendioOssman** [comment] 2022-06-23 13:46
> * The delay occurs within the normal X11 `WaitForSomething()` function, and it appears to be related to a timer.  (I'm not sure which timer.)

That's odd. That should release as soon as there is any activity from either an X11 or VNC client.

> * However, it doesn't become responsive until about 30-60 seconds after the server rejects the huge clipboard update from the first viewer.

That's massively too late. I wonder why I'm not seeing this. I need to play around with more scenarios here and see if I can get the same effect.

> * I can't reproduce the issue with a Linux client

Large clipboards require support for INCR on Linux, and FLTK might not handle that.

**Comment by CendioOssman** [comment] 2022-06-27 05:56
I'm still failing to reproduce this with a macOS client, but I got the issue with a Windows client. I didn't have time to dig too deep, but an strace shows that there is some issue with data not being delivered from the client to the server properly. So the congestion control locks up as it doesn't get the responses to the fences as expected.

It behaves as if TCP_CORK gets stuck on. But since that is a client side thing, I fail to see how more than one client gets affected.

**Comment by CendioOssman** [comment] 2022-06-28 12:54
So I found one bug (ff9ccc21b8c66008a99f07b36cccb1a952a340ae). It only happens when TLS is used, though. But I can reproduce it on Linux in that case.

Could that be the same issue you are seeing? Has TLS been used whenever you see the problem?

It doesn't directly explain other clients being affected, though. I haven't tested that scenario yet.

**Comment by dcommander** [comment] 2022-06-28 13:49
I was using TLS when the issues were observed.  I will try your new patch.

**Comment by dcommander** [comment] 2022-06-28 14:18
The new patch seems to fix the issue, from my point of view.  As far as other connected viewers being affected, I was testing with multiple viewers connecting from the same client.  I don't have any data to indicate whether that aspect of the issue was reproducible with multiple viewers connecting from different clients.

**Comment by CendioOssman** [comment] 2022-06-28 14:19
But just to clarify, you're not seeing any issues with any of the clients with the patch in place?

**Comment by CendioOssman** [comment] 2022-06-29 06:03
Great! Thanks for testing! The changes are now merged.

**Closed by CendioOssman** 2022-06-29 06:03 UTC
Labels: bug
