### ISSUE TITLE
Toolbar menu hidden

### ISSUE THREAD

**Issue by agiuffre** [TigerVNC/tigervnc#1180] opened 2021-01-12 17:40 UTC
TIGERVNC Display issue:
The toolbar menu on all of my applications seem to be hidden. I cannot exit, minimize, change size of applications or move them around in my window. I cannot access my home button, or open any other application unless done through terminal. Switching in/out of fullscreen, changing the resolution, does not work. Cannot access preferences. 

Fn8 opens a preferences menu; option to refresh screen, change resolution, none seem to work. 

**To Reproduce**
Not sure if this was an error going in/out of full screen mode. 

**Screenshots**
Screenshot attached. Menu bar on terminal window is not visible. Cant move terminal window, open or close it without using shortcut keys. 

**Client (please complete the following information):**
 - OS: MacOS Mojave Version 10.14.5
 - VNC client: TigerVNC
 - VNC client version: TigerVNC version 1.11.0
 - Client downloaded from: Oxford GitHub

**Server (please complete the following information):**
 - OS: Windows 
 - VNC server: TigerVNC 
 - VNC server version: TigerVNC version 1.11.0
 - Server downloaded from: TigerVNC version 1.11.0
 - Server was started using: ssh localhost
 - 
![Screen Shot 2021-01-12 at 8 56 21 AM](https://user-images.githubusercontent.com/61321454/104351256-68964800-54c2-11eb-943b-d47d6d2e373a.png)

**Comment by CendioOssman** [comment] 2021-01-18 13:00
Duplicate of #1181.

**Closed by CendioOssman** 2021-01-18 13:00 UTC
Labels: winVNC
