### ISSUE TITLE
x0vncserver does not update window on client when using offset on secondary display

### ISSUE THREAD

**Issue by chaitan3** [TigerVNC/tigervnc#748] opened 2018-10-20 01:36 UTC
I have x0vncserver running with the following command:

x0vncserver :0 -passwdfile ~/.vnc/passwd -rfbport 5900 -geometry 2880x1800+3840+0

When using the following to connect with the server through an ssh tunnel:

vncviewer -RemoteResize=0 :0 

I can see the screen initially, but do not see any updates on the screen. When I move the mouse or use the keyboard I can see the changes on the physical screen. My setup involves 2 displays: A 3840x2160 screen on the left and a 2880x1800 screen on the right.

I am using tigervnc 1.9.0 on Ubuntu 18.04 with Nvidia drivers 410.66

Any help would be appreciated. Thanks.

**Comment by CendioOssman** [comment] 2018-10-23 13:09
Are you saying that the problem goes away if you remove the `-geometry` flag?

And could you test a nightly build? You can find them on the homepage.

**Comment by chaitan3** [comment] 2018-10-23 21:29
I retested with the nightly build and see no difference.

If I remove the geometry flag, then the display defaults to 1920x1080+0+0 and I can see updates to the screen. If geometry is explicitly set to "1920x1080+0+0" or "1920x1080+1920+0" (hence displaying partial content of the left display), then the screen updates. If it is set to 1920x1080+3840+0 (hence displaying partial content on right display), then it does not update. What is funny is if I set geometry to 1920x1080+2880+0 (screen is split between two displays), then the left half of the vnc screen updates and the right half does not. In my setup, the left display is primary and the right display is secondary. My window manager is i3.

**Comment by CendioOssman** [comment] 2018-10-25 08:31
Hang on, if you're not getting both monitors without `-geometry` then you have something wrong with your X server. Is it started in zaphod mode where you cannot move windows between the monitors?

**Comment by chaitan3** [comment] 2018-10-26 20:38
I think I made a mistake when running without the geometry option. I retested without the geometry option and I now see a vnc screen with both my displays side by side and the content on both displays does update. So, it seems to be an issue with the geometry option which focuses on the secondary display on the right.

**Comment by chaitan3** [comment] 2018-10-27 04:36
Just wanted to add that I am not using zaphod mode.

**Comment by chaitan3** [comment] 2018-10-30 19:35
I was able to reproduce the issue on another dual monitor setup (left: 2560x1440, right: 1920x1200) using XFCE 4.12 on Ubuntu 18.04 with Intel drivers. Using the geometry option to produce a vnc screen for the left display works (meaning that the screen updates), while producing a vnc screen for the right display does not work.

**Comment by CendioOssman** [comment] 2018-10-31 16:25
Hmm... I'm afraid I cannot reproduce this here on my machine. It's a Fedora 28 machine with two monitors and an Intel card.

Could you try with a nightly build of x0vncserver?

**Comment by chaitan3** [comment] 2018-11-04 06:05
I tried with a nightly build and it does not work. It's weird that it works for you and not me. Oh well, is there a way I can restrict the client to only display a part of the screen rather than doing it client side?

**Comment by CendioOssman** [comment] 2018-11-05 15:48
No, I'm afraid we do not have any such settings. At best you can resize the window and scroll it around so you only get the parts you want.

**Comment by CendioOssman** [comment] 2018-11-05 15:51
Hang on, it seems like GNOME is hiding a bug here. I redid the test with Xfce on the server and now I can see the issue. It should be fixed in 785cb9d837d2baefae852866c67e5d3de49dd2c1.

**Closed by CendioOssman** 2018-11-05 15:51 UTC
