### ISSUE TITLE
Implement cursor grabbing

### ISSUE THREAD

**Issue by warmos** [TigerVNC/tigervnc#423] opened 2017-02-27 14:30 UTC
Client could update the users cursor based on remote cursor. This can be used for 3D applications such as blender since tigervnc is really fast. I got almost 50fps on 20mbit network.
Thanks

**Comment by CendioOssman** [comment] 2020-04-02 09:29
Marking as duplicate of #619.

**Closed by CendioOssman** 2020-04-02 09:29 UTC
Labels: enhancement
