### ISSUE TITLE
File transfer support

### ISSUE THREAD

**Issue by nickbe** [TigerVNC/tigervnc#419] opened 2017-02-23 11:19 UTC
Has anyone tried to reactivate the long gone file transfer?
Without this I still can't use TigerVNC in most cases and fall back to TightVNC.

It would be be great to see this feature coming along.

**Comment by CendioOssman** [comment] 2017-02-23 12:05
I'm afraid I don't know anyone working on this, no.

**Comment by nickbe** [comment] 2017-02-23 15:56
According to these old conversations:
https://www.mail-archive.com/tigervnc-devel@lists.sourceforge.net/msg00252.html

File transfer was already there at one point, but then removed.
Maybe the function could be reused somethow

**Comment by CendioOssman** [comment] 2017-02-24 08:56
We already have an issue for this. Closing as a duplicate of #323.

**Closed by CendioOssman** 2017-02-24 08:56 UTC
Labels: enhancement
