### ISSUE TITLE
Windows showed that The Signing Certificate for version 1.12.0  execution files are invalid and have a risk of being modified.

### ISSUE THREAD

**Issue by KamMedia** [TigerVNC/tigervnc#1533] opened 2022-10-11 03:01 UTC
**Describe the bug**
Windows showed that The Signing Certificate for version 1.12.0 execution files are invalid.

**To Reproduce**
1. Download the exe files
2. Check the Signing Certificate of the exe files.
3. Windows showed that the Signing Certificate are invalid and have a risk of being modified.

**Expected behavior**
A valid Signing Certificate

**Screenshots**

**Client (please complete the following information):**
 - OS: WIN10

**Comment by CendioOssman** [comment] 2022-10-11 06:29
@bphinz?

**Comment by bphinz** [comment] 2022-10-11 08:30
This sounds like a duplicate of #1503. @KamMedia, can you please confirm that the issue you describe is no longer present with the latest nightly build?

**Comment by KamMedia** [comment] 2022-10-11 09:57
Hello bphinz,

I can confirmed that the Signing Certificate issue has been fixed with latest nightly build version. 

Best Regards,
Kam

**Closed** 2022-10-11 19:20 UTC
Labels: bug, duplicate
