### ISSUE TITLE
VNCserver - can't see menu to minimize, close, etc

### ISSUE THREAD

**Issue by agiuffre** [TigerVNC/tigervnc#1178] opened 2021-01-12 06:05 UTC
Toolbar is hidden from all applications when open. Can't move applications within window, option to do so isn't available. 
Can't minimize or close any applications unless shortcuts are used. 
Refreshing screen, changing resolution, or going in and out of full screen mode doesn't work. 
Can't get to home options - open different applications, etc.

**Comment by CendioOssman** [comment] 2021-01-12 15:19
Please use our issue bug form and fill out all the fields so we can better understand what your environment looks like.

**Comment by CendioOssman** [comment] 2021-01-18 13:00
Duplicate of #1181.

**Closed by CendioOssman** 2021-01-18 13:00 UTC
