### ISSUE TITLE
tigervncviewer on windows needs to copy twice in order to get clipboard copied to the server

### ISSUE THREAD

**Issue by xsm1997** [TigerVNC/tigervnc#1586] opened 2023-01-22 16:10 UTC
**Describe the bug**
tigervncviewer on windows needs to copy twice in order to get clipboard copied to the server.

**To Reproduce**
1. connect to vnc server
2. copy something in Windows (e.g., abc)
3. paste in server
4. successfully pasted
5. copy another thing in Windows (e.g., def)
6. paste in server
7. "abc" is pasted in server
8. copy the text again in Windows (def)
9. paste in server
10. "def" is pasted successfully

The issue is: after connecting to server, the even times of copy will not works. The odd times of copy works normally. This issue can be reproduced stably when using tigervnc-standalone-server and tigervncviewer64. But when using realvnc as viewer, the issue disappeared.

**Expected behavior**
copy & paste works normally every time I copied.

**Screenshots**

**Client (please complete the following information):**
 - OS: Windows 11 22H2 (insider beta, build 22623.1180)
 - VNC client: TigerVNC
 - VNC client version: 1.12.0, 1.11.0, 1.13.0 beta
 - Client downloaded from: SourceForge

**Server (please complete the following information):**
 - OS: Debian 11
 - VNC server: TigerVNC
 - VNC server version: 1.11.0, 1.12.0
 - Server downloaded from: my Linux distribution
 - Server was started using: vncserver

**Additional context**
I use kde-plasma-5 as my DE and use a custom xstartup file including dbus-launch to start the X server. Even I do not start vncconfig the odd times of copy works normally. I do not know if that is a normal behavior nor if that has something to do with the issue. Also, starting vncconfig manually cannot solve the issue.

**Comment by CendioOssman** [comment] 2023-01-26 10:17
I'm afraid I was unable to reproduce the issue here.

Which applications were you using on the Windows and Linux side? And exactly how did you do the copying and pasting?

Could you test with a more minimal environment, e.g. just xterm or just konsole. KDE has had some weird interactions with the clipboard historically that could complicate debugging.

**Comment by xsm1997** [comment] 2023-01-26 10:30
Thanks for the reply.

I will try to reproduce the issue using a fresh-installed windows 11 and an xterm or Konsole later. Will report the results later.

**Comment by L-U-T-i** [comment] 2023-01-27 10:12
I've noticed something similar on Rocky 9.1 linux (somewhere in the mid of 2022; before there were no such issues with the same version 1.12.0 on Rocky 8), therfore I've rebuilt the latest git commit 7c288cf at that time (Oct 27 2022).

It was slightly better after that, but from time to time it still happens (I've noticed sometimes the old clipboard content is pasted instead of just copied one, but I haven't paid enough attention to find the pattern by now...).

I've just rebuilt the latest commit bf0fb91 as of today (Jan 17 2023) and I'll report if there will be some change.

But in any case, it seems it is related (also) to some dependencies (as said, no problems on Rocky 8, but appeared on the same - just rebuilt - 1.12.0 on Rocky 9.0).

**Comment by xsm1997** [comment] 2023-02-07 13:28
Tests on xterm shows it is a problem related to KDE. Only starting xterm without KDE does not have the issue.

It seems it is an issue with both tigervnc and KDE. Feel free to close the issue if not related.

**Comment by CendioOssman** [comment] 2023-02-13 13:45
KDE is popular enough that we want to at least understand the problem, and see if there is something we can tweak.

Let me see if I can get a test system up and see if I can reproduce the problem here.

Have you reported this issue to Debian or KDE?

**Comment by xsm1997** [comment] 2023-02-13 14:34
> KDE is popular enough that we want to at least understand the problem, and see if there is something we can tweak.
> 
> Let me see if I can get a test system up and see if I can reproduce the problem here.
> 
> Have you reported this issue to Debian or KDE?

No, I haven't reported the issue to Debian nor KDE.

I will also test it on Debian testing and Ubuntu 22.04, to see whether a newer version of KDE has the issue.

**Comment by Groovylein** [comment] 2023-03-14 13:13
Might be related to Windows 11. A colleague does not have this problem with Windows 10

**Comment by xsm1997** [comment] 2023-05-09 04:12
Tried more combinations.

Debian 11 (server) + KDE + Windows 10 22H2 (client): has problems
Debian 12 (server) + KDE + Windows 11 22H2 (client): has problems
Debian 12 (server) + KDE + Windows 11 insider Dev (client): has problems
Debian 12 (server) + GNOME + Windows 11 insider Dev (client): has problems
Ubuntu 22.04 (server) + KDE + Windows 11 22H2 (client): has problems

All has problems. Need to copy twice.

Tried package from Debian using Xstartup script, and package from sourceforge.net (deb) with .vnc/config file. No luck.

**Comment by xsm1997** [comment] 2023-05-09 04:18
Update: if I uncheck Accept clipboard from server in the options of VNC Viewer, the problem disappeared. Paste can works every time I copy in the client.

**Comment by Groovylein** [comment] 2023-05-09 09:24
> Update: if I uncheck Accept clipboard from server in the options of VNC Viewer, the problem disappeared. Paste can works every time I copy in the client.

That worked for me as well, but then I am not able to copy strings from VNC to Windows 😞

**Comment by CendioOssman** [comment] 2023-09-08 14:16
I was able to reproduce it now using an Ubuntu 22.04 with KDE. Let me investigate and see if I can figure out what is going on.

**Comment by CendioOssman** [comment] 2023-09-08 14:26
The issue is with KDE's "Prevent empty clipboard" feature. What happens is:

1. You copy something on the client
2. vncviewer notices this and notes that it should inform the server once it has focus
3. vncviewer gets focus
4. vncviewer informs the server there is new clipboard data available
5. You request to paste the data on the server
6. vncviewer sends the clipboard data
7. You switch to something else on the client and copy something else
8. vncviewer notices this and notes that it should inform the server once it has focus. **BUT** it can no longer keep sending the old data as that data has been dropped from the client clipboard. It thus informs the server right away that it has no clipboard.
9. KDE sees that the clipboard is abandoned and injects a copy of the old data.
10. vncviewer is informed that there is clipboard data on the server and drops the local client clipboard

This is messy, so I need to think about what we should be doing at this point.

**Comment by CendioOssman** [comment] 2023-09-08 14:27
As a note, it works better on Linux clients because there are two clipboards there. So the bug will happen when you select something (filling the selection clipboard), but then resolve itself if you then fill the normal clipboard.

You see the same buggy behaviour on Linux if you use just the selection clipboard.

**Comment by CendioOssman** [comment] 2023-09-11 11:12
Fixed in 8d2739fa71eaf7a28d63ac62583e8087c66a5247. We'll now simply ignore the server when vncviewer doesn't have focus. Hopefully, this matches user expectations better.

**Closed by CendioOssman** 2023-09-11 11:12 UTC
Labels: bug

**Comment by otofoto** [comment] 2023-09-13 18:17
Also it stops working in longer sessions. Need to reconnnect to client to restart clipboard.

**Comment by otofoto** [comment] 2024-05-29 10:53
Crashes my used program after reconnect. 

So when clipboard is not working I try to reconnect and copy again which results in crash. Haven't noticed such issue when working not remotely.

![image](https://github.com/TigerVNC/tigervnc/assets/26463333/17db99b6-52f8-4008-9d46-9debf8657286)

**Comment by L-U-T-i** [comment] 2024-08-18 10:59
It seems this old issue is reppearing occasionlly as well:
https://github.com/TigerVNC/tigervnc/issues/1251#issuecomment-2295218082
