### ISSUE TITLE
Invalid Pixel Format when user does not exist on server

### ISSUE THREAD

**Issue by kaelfischer** [TigerVNC/tigervnc#1703] opened 2023-12-11 05:39 UTC
Attempting to connect to sever using invalid user gives misleading error: Invalid Pixel Format. 

1. connect to server
2. mistype your username
3. enter a password
4. click OK

**Expected behavior**
Some sort of authentication error would help users figure out the problem.

**Client:**
 - OS: Windows 10
 - VNC client: TigerVNC
 - VNC client version: 1.13.1
 - Client downloaded from: tigervnc.org

**Server:**
 - OS: raspios-bullseye (2023-05-3)
 - VNC server: wayvnc 
 - VNC server version:
     wayvnc --version 
     
     wayvnc: 0.7.2
     neatvnc: 0.7.1
     aml: 0.3.0

 - Server downloaded from: bundled with OS
 - Server was started using: starts with x session
 - 
**Additional context**
This behavior was noted in a comment in another issue: 
https://github.com/TigerVNC/tigervnc/issues/1679#issuecomment-1806992823

**Comment by CendioOssman** [comment] 2023-12-12 14:37
It sounds like the server is sending something unexpected.

Like #1679, could you test with TightVNC so we can see if we can get a similar log with the pixel format?

**Comment by CendioOssman** [comment] 2023-12-12 14:53
I tried testing the same versions of wayvnc and neatvnc here on Fedora, and I'm afraid I cannot reproduce the issue.

How way wayvnc configured in your setup?

**Comment by kaelfischer** [comment] 2023-12-13 17:53
I use the out of the box wayvnc configuration.

Unfortunately wayland made my java-based bloated IDE impossible to use and I have switched to X11. So I can't test in my old setup any longer. 

I won't close this, because I believe it is a problem, and you might want to track it.

**Comment by CendioOssman** [comment] 2023-12-15 08:14
I'm afraid we can't really progress with the issue if we cannot replicate it. So I'll close this for now, and we can continue debugging if more users experience the issue.

**Closed by CendioOssman** 2023-12-15 08:14 UTC

**Comment by vnd** [comment] 2024-11-26 09:49
Can confirm this issue.

Client: tigervnc-viewer 1.12
Server: weston with VNC backend running on an embedded board

I've mistyped password and got 'invalid pixel format' error.
