### ISSUE TITLE
Windows 11 Clipboard

### ISSUE THREAD

**Issue by evgeniyBolnov** [TigerVNC/tigervnc#1439] opened 2022-03-03 09:32 UTC
**Describe the bug**
After switching window to the Viewer, the client's clipboard is overwritten with clipboard data from the server.

**To Reproduce**
1. Ctrl+C on Client
2. Switch window to Viewer
3. Ctrl+V on Server
4. See what pasted server clipboard data
5. Switch on Client and Ctrl+V
6. See what pasted server clipboard data

**Expected behavior**
Copy from Client and Paste on Server, and reverse

**Client:**
 - OS:  Windows 11
 - VNC client: TigerVNC
 - VNC client version: 1.12.0
 - Client downloaded from: GiHub

**Server:**
 - OS: CentOS 7.9
 - VNC server: TigerVNC
 - VNC server version: 1.8.0
 - Server downloaded from: Linux distribution
 - Server was started using: vncserver

**Comment by CendioOssman** [comment] 2022-03-07 08:34
That's a very old server. I don't suppose you have access to something more recent to test?

**Comment by evgeniyBolnov** [comment] 2022-03-07 08:47
Unfortunately, I do not have access to manage the software on the server. I forgot to clarify a little: this problem does not manifest itself on Windows 10

**Comment by CendioOssman** [comment] 2022-03-08 15:04
That's very odd. Let's see if I can find some time to test it on the Windows machines here.

**Comment by evgeniyBolnov** [comment] 2022-03-08 15:28
> That's very odd. Let's see if I can find some time to test it on the Windows machines here.

Thank you. before writing here, I also checked on various computers with Windows 10 and 11

**Comment by CendioOssman** [comment] 2022-03-30 15:22
I'm afraid I could not reproduce the issue here, so there is some detail that is missing.

My server was RHEL 7 with tigervnc-server-1.8.0-22.el7.x86_64.

My client was Windows 11 with vncviewer64.exe 1.12.0 downloaded from our release page.

I did:

1. Open notepad on Windows, write some text and copy it using Ctrl+C
2. Open gedit in VNC, press Ctrl+V

I then did the opposite copying from gedit to notepad. Both cases worked fine.

**Comment by evgeniyBolnov** [comment] 2022-03-30 15:55
I think we found the problem, but a few new ones appeared 🙂. The problem is what layout is on the host: if it differs from English, nothing works. there is also a problem with inserting text in Cyrillic - instead of text, a question mark character, but I'm not sure if this is a client problem.

**Comment by CendioOssman** [comment] 2022-03-31 06:38
Alright, I'll go ahead and close this issue then.

Your other problems sound like #20 or #93 so please have a look at them.

**Closed by CendioOssman** 2022-03-31 06:38 UTC
