### ISSUE TITLE
1.5 64bit windows binaries seem completely broken

### ISSUE THREAD

**Issue by calestyo** [TigerVNC/tigervnc#234] opened 2015-11-08 18:17 UTC
Hey.

I upgraded from 1.4.3 to 1.5... and with that nothing works anymore.
Connections neither work via server nor as service, the program (neither setup nor the -register) do actually register a service.
Uninstalling doesn't clean up correctly either.

Even after manually cleaning up everything (program files, registry, sc delete'ing all left over services) and freshly installing again... the same.

Switching back to 1.4.3 and everything works again.

Cheers,
Chris.

**Comment by calestyo** [comment] 2015-11-08 18:17
(oh that's under win 8.1 64bit)

**Comment by CendioOssman** [comment] 2015-11-09 09:43
This could be #187 which was fixed with f7aa3f9bd315ba52d6ee1e7236a580102c8d20b8. Can you test a nightly build and see if that works?

**Comment by FoLkjF** [comment] 2015-11-21 22:14
same on Win 7 x64 vnc ver: 1.5.0

will try a nightly build

**Comment by hackonteur** [comment] 2015-11-27 17:57
Also true of 1.6.0beta 64-bit

    Problem signature:
    Problem Event Name:	APPCRASH
    Application Name:	vncviewer64-1.5.90.exe
    Application Version:	1.5.90.0
    Application Timestamp:	02bfec18
    Fault Module Name:	vncviewer64-1.5.90.exe
    Fault Module Version:	1.5.90.0
    Fault Module Timestamp:	02bfec18
    Exception Code:	c0000005
    Exception Offset:	00000000001d0200
    OS Version:	6.1.7601.2.1.0.256.4
    Locale ID:	2057
    Additional Information 1:	d5dc
    Additional Information 2:	d5dcc4555dd7f12e1e4cd0af09e83927
    Additional Information 3:	71c4
    Additional Information 4:	71c49345063ca1d2a18ce30a04e77127

**Comment by hackonteur** [comment] 2015-11-27 18:07
Nightly fails for me too (both 32 and 64-bit versions):

    Faulting application name: vncviewer.exe, version: 1.6.80.0, time stamp: 0x00000021
    Faulting module name: ntdll.dll, version: 6.1.7601.17725, time stamp: 0x4ec49b8f
    Exception code: 0xc0000005
    Fault offset: 0x000222b2
    Faulting process id: 0x2984
    Faulting application start time: 0x01d1293da9c91837
    Faulting application path: C:\Users\sroland\Downloads\vncviewer.exe
    Faulting module path: C:\Windows\SysWOW64\ntdll.dll
   Report Id: e783eb6c-9530-11e5-b6e9-5ce0c5c40f8a

**Comment by fluffypony** [comment] 2015-11-30 08:49
Can confirm that nightly is failing for me on Windows 10 ("Windows with Bing", which is the Home edition that Bay Trail etc. tablets get), 32-bit, same error. It fails to run as a service or in user mode.

**Comment by CendioOssman** [comment] 2015-11-30 09:19
I can confirm that the official builds are broken in some regard. They refuse to even start for me, not even a crash dialog. My own builds work fine though, so it seems like it is a build system issue.

@bphinz, are the nightlies and the beta working for you?

**Comment by bphinz** [comment] 2015-11-30 12:40
I'll take a look when I get home tonight. I did just verify the other day
that the build host (fedora 21) is fully updated. I'll review the build
logs to see if there any suspicious warnings too.

-Brian

**Comment by bphinz** [comment] 2015-12-01 05:24
This is about the only thing that I see in the build logs:

...

Scanning dependencies of target installer
fixme:winediag:start_process Wine Staging 1.7.44 is a testing version
containing experimental patches.
fixme:winediag:start_process Please report bugs at
http://bugs.wine-staging.com (instead of winehq.org).
fixme:ole:RemUnknown_QueryInterface No interface for iid
{00000019-0000-0000-c000-000000000046}
fixme:process:SetProcessDEPPolicy (1): stub
fixme:process:SetProcessDEPPolicy (1): stub

...


Haven't had a chance to track this down and see if it's meaningful
however.  I installed some additional packages on the build host so that
'wine --check-libs' does not have any missing libraries but haven't tested
the resulting builds to verify if it made any difference.

-brian

**Comment by CendioOssman** [comment] 2015-12-01 10:08
Aren't you using wine to build the installer? If so then it isn't relevant here. No binaries work, not even the simple vncviewer-1.5.90.exe one.

We've had people test these fairly recently, so something must have changed. Have you run any updates? Do any binaries work? Do you have a Windows machine to test on? :)

**Comment by bphinz** [comment] 2015-12-01 16:21
On Tue, Dec 1, 2015 at 5:08 AM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> Aren't you using wine to build the installer? If so then it isn't relevant
> here. No binaries work, not even the simple vncviewer-1.5.90.exe one.
>
I am using wine.


> We've had people test these fairly recently, so something must have
> changed. Have you run any updates? Do any binaries work? Do you have a
> Windows machine to test on? :)
>
I updated a couple of libraries (libpng, gnutls, etc) to the latest
upstream versions late last week, but they all compiled fine and the same
thing was done for the builds on all other platforms.  I didn't realize
that even the viewer was borked, but I don't think that was true when the
OP submitted the ticket so I think we're dealing with multiple issues.  In
either case, the build host is running f20 (not f21 as I erroneously stated
before), which has been EOL'd so it's due for an update anyway.  I finally
got around to making the el5 and el6 builds modular and I was planning to
use the capacity that was freed up by that to stand up a pair of el7 build
hosts, so I'll start making preparations to migrate the windows builds to
el7.  Nearly all of the relevant mingw & wine packages on el7 are newer, so
that should be beneficial.

I do have a Win 7 machine that I can test on, so I'll try to do some
debugging on the current builds tonight as well.

-brian

**Comment by CendioOssman** [comment] 2015-12-01 17:06
Somewhat related, have you looked at some way to have builds with debug symbols as well? For the RPM stuff it should be easy enough to produce debuginfo packages. For Windows I guess it'll have to be separate binaries.

**Comment by bphinz** [comment] 2015-12-01 17:17
On Tue, Dec 1, 2015 at 12:06 PM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> Somewhat related, have you looked at some way to have builds with debug
> symbols as well? For the RPM stuff it should be easy enough to produce
> debuginfo packages. For Windows I guess it'll have to be separate binaries.
>
Yeah, for the RPMs that's trivial, I have them disabled by default but can
turn them back on.  I may need some help with WIndows and OS X though.

**Comment by bphinz** [comment] 2015-12-03 17:11
On Tue, Dec 1, 2015 at 11:21 AM, Brian Hinz wrote:

> On Tue, Dec 1, 2015 at 5:08 AM, Pierre Ossman (Work account) <
> notifications@github.com> wrote:
>
>> Aren't you using wine to build the installer? If so then it isn't
>> relevant here. No binaries work, not even the simple vncviewer-1.5.90.exe
>> one.
>>
> I am using wine.
>
>
>> We've had people test these fairly recently, so something must have
>> changed. Have you run any updates? Do any binaries work? Do you have a
>> Windows machine to test on? :)
>>
> I updated a couple of libraries (libpng, gnutls, etc) to the latest
> upstream versions late last week, but they all compiled fine and the same
> thing was done for the builds on all other platforms.  I didn't realize
> that even the viewer was borked, but I don't think that was true when the
> OP submitted the ticket so I think we're dealing with multiple issues.  In
> either case, the build host is running f20 (not f21 as I erroneously stated
> before), which has been EOL'd so it's due for an update anyway.  I finally
> got around to making the el5 and el6 builds modular and I was planning to
> use the capacity that was freed up by that to stand up a pair of el7 build
> hosts, so I'll start making preparations to migrate the windows builds to
> el7.  Nearly all of the relevant mingw & wine packages on el7 are newer, so
> that should be beneficial.
>

Ugh.  It turns out that el7/EPEL does not provide a 32-bit version of wine
(necessary to run Inno Setup), and it apparently it takes considerable
effort build one on that platform.  So instead, I stood up a new Fedora 23
build host last night.  I still have to go through and re-package all the
statically linked libraries, so it's be another day or so before I can
produce a new set of binaries.

-brian

**Comment by bphinz** [comment] 2015-12-06 17:06
On Thu, Dec 3, 2015 at 12:11 PM, Brian Hinz wrote:

> Ugh.  It turns out that el7/EPEL does not provide a 32-bit version of wine
> (necessary to run Inno Setup), and it apparently it takes considerable
> effort build one on that platform.  So instead, I stood up a new Fedora 23
> build host last night.  I still have to go through and re-package all the
> statically linked libraries, so it's be another day or so before I can
> produce a new set of binaries.
>

There are new binaries posted to the nightlies page.  These are built
from db821a2, since the following commit seems to have broken el5 builds.
The windows viewers appear to be working now, but the server still seems
utterly broken.  Connections simply fail, the "About…" dialog from the tray
icon does nothing, and if I attempt to add a local subnet address to the
Access Control list (Properties -> Connections -> Access Control -> Add), I
get a warning dialog that says "unable to resolve the host by name: Either
the application has not called WSAStartup, or WSAStartup failed.".

-brian

**Comment by bphinz** [comment] 2015-12-06 18:20
One thing that I just noticed is that the name of the service (as displayed in the Control Panel/Services console) was changed from "VNC Server Version 4" to "Provides remote access to this machine via the VNC/RFB protocol." in commit bc84faa.  However on my Win 7 system both of them were showing up and only "VNC Server Version 4" was getting started.  This was after uninstalling, rebooting, and re-installing.  If I stopped the VNC Server Version 4" service and tried to start "Provides remote access to this machine via the VNC/RFB protocol.", it failed with "Error 2: The system cannot find the file specified.".  Furthermore, after installing the 32-bit version and then subsequently installing the 64-bit version on the same machine, I found that the new service definition still had the path to the 32-bit executable defined.  After manually deleting the old registry keys, rebooting, and then re-installing the latest nightly, everything seems to be working again.  So it looks to me like maybe the uninstaller is not correctly removing the service definitions (or maybe it only fails to do so during an upgrade?). 

-brian

**Comment by CendioOssman** [comment] 2015-12-07 10:30
> There are new binaries posted to the nightlies page. These are built from db821a2, since the following commit seems to have broken el5 builds. The windows viewers appear to be working now, but the server still seems utterly broken. Connections simply fail, the "About…" dialog from the tray icon does nothing,

This works just fine for me.

> and if I attempt to add a local subnet address to the Access Control list (Properties -> Connections -> Access Control -> Add), I get a warning dialog that says "unable to resolve the host by name: Either the application has not called WSAStartup, or WSAStartup failed.".

This however I also see. I also see it in my builds so it is probably not just a build issue. But you opened #248 for this so let's continue there.

> One thing that I just noticed is that the name of the service (as displayed in the Control Panel/Services console) was changed from "VNC Server Version 4" to "Provides remote access to this machine via the VNC/RFB protocol." in commit bc84faa.

Confusing API. We have issue #209 for this.

> So it looks to me like maybe the uninstaller is not correctly removing the service definitions (or maybe it only fails to do so during an upgrade?). 

Upgrades in Windows generally suck. It's not really like package management on Linux. Any upgrades need to be explicitly handled in the installer, which I assume they aren't. Same thing for uninstallation.

**Comment by CendioOssman** [comment] 2015-12-07 10:30
So is the issue here resolved? Close this perhaps then and update the beta binaries?

**Comment by hackonteur** [comment] 2015-12-08 10:34
32 and 64-bit viewer nightlies work for me in Windows 7. (I never tested the server.)

**Closed** 2015-12-09 10:14 UTC

**Comment by calestyo** [comment] 2022-12-23 23:38
btw: Can also confirm that this works with at least 1.12.0.

**Comment by phil123456** [comment] 2023-07-25 15:20
on Win 10 with the freshly downloaded tigervnc64-1.13.80.exe

Faulting application name: vncviewer.exe, version: 1.13.80.0, time stamp: 0x64b5fd21
Faulting module name: vncviewer.exe, version: 1.13.80.0, time stamp: 0x64b5fd21
Exception code: 0xc0000005
Fault offset: 0x00000000002b4023
Faulting process ID: 0x383c
Faulting application start time: 0x01d9bf0b3aaf9ec7
Faulting application path: P:\Program Files\TigerVNC\vncviewer.exe
Faulting module path: P:\Program Files\TigerVNC\vncviewer.exe
Report ID: 82b06df0-73ef-4ddd-ad03-03e76fd7d80e
Faulting package full name: 
Faulting package-relative application ID:
