### ISSUE TITLE
(fix) prevents display number change after server crash and restart

### ISSUE THREAD

**Issue by atesin** [TigerVNC/tigervnc#527] opened 2017-10-20 16:52 UTC
this applies to 'vncserver' linux version (perl script)

```diff
723,730d722
<         # 'vncserver -kill' remove lock file patch, oct2017 atesin&gmail,com
<         # prevents display number change after server crash and restart
<         # insert this in 'sub Kill' just before 'if (! -r $pidFile) {'
<         ($lockFile = "/tmp/.X".$opt{'-kill'}."-lock") =~ s/://;
<         if (-e $lockFile) {
<             unlink $lockFile;
<             die "\nCan't find file $pidFile\nBut lock file ".$lockFile." found and removed\n\n";
<         }
```

**Comment by hildred** [comment] 2017-10-20 17:04
On Fri, Oct 20, 2017 at 10:52 AM, atesin <notifications@github.com> wrote:

> this applies to 'vncserver' linux version (perl script)
>
>
> A bare diff is hard to read and hard to patch with especially if there
have been other changes. The unified diff format is much easier in all
regards. You can make a unified diff with diff -u. Even better is a git
style diff or a pull request. If you would resubmit in one of those formats
and include the version you are diffing against we would be able to
evaluate your changes.

-- 
--
Ben Hildred
Automation Support Services

**Comment by atesin** [comment] 2017-10-20 18:29
you can also locate lines specified in comments and insert block by hand

strangely, the fix works flawlessly by running manually, but with systemd 'ExecStartPre' option it doesnt work

**Comment by atesin** [comment] 2017-10-20 18:59
dirty workaround with systemd.. i am tired to lose connectivity on every server crash

add this line to /etc/systemd/system/vncserver@:<display>.service as first ExecStartPre option
replace <display> with your display number (no colon), and reload daemons

ExecStartPre=-/usr/bin/rm /tmp/.X<display>-lock /tmp/.X11-unix/X<display>

**Comment by CendioOssman** [comment] 2017-10-23 14:37
I'm afraid I don't understand the scenario here. If the X server crashes, then it should clean up any stray sockets already when you use `-kill`. When does this not work?

**Comment by atesin** [comment] 2017-10-23 17:44
i meah when WHOLE linux server crashes, because an energy loss or kernel panic for example

i am afraid "-kill" option does not delete lock files on /tmp/ folder ("vncserver" perl script)... i think Xvnc does, and that's ok because tcp port could being used...  but when linux server suddenly crashes Xvnc has no time to delete lock files and cleanup things, so when linux server comes back vncserver thinks Xvnc are still up and running

i think there should be a better way of knowing if port is being used, for example with "netstat -lp" or "ps --foo | grep bar" ... that way you will REALLY know if effectively vnc is up and running and listening, with no need of write/read lock files

**Comment by CendioOssman** [comment] 2017-10-24 07:19
`vncserver` already has code to do exactly what you want. Look at lines 760-772. So you must be hitting some bug, or there is some more detail missing in your scenario.

Given your patch it seems like the pid file is removed for some reason. Do you have some special cleanup that could explain this?

**Comment by MarkMielke** [comment] 2017-10-24 08:23
Total coincidence that I experienced an extreme version of this last Thursday affecting some 10 or so machines of 100. The scenario wasn't actually a loss of power, but a loss of disk access. The network team was adding another pair of switches to our network topology and introduced a loop by accident. It took about 2.5 minutes for them to realize what was wrong and then get down to the data center and break the loop by physically disconnecting the fiber. Once the link was down, the fail over brought the network back up, but many of the virtual machines gave up waiting, and marked the iSCSI volumes as read-only, and required a reboot to clear. On reboot, the /tmp files were left around on 10 of the machines, and this prevented.

I haven't had time to really think through how to resolve the problem, as it is pretty rare. But, my starting position would be the elimination of race conditions, and ensuring that the code would handle all the different possibilities. I don't think I am in favour of arbitrarily removing the files on startup. But, the current code clearly does have a gap. This would be on TigerVNC 1.8.0.

**Comment by atesin** [comment] 2017-10-24 15:42
@CendioOssman :

thank for looking the file, but lines 760-772 matches a comment block in my "vncserver" script (centos7 base repo, tigervnc-server-1.8.0-1.el7.x86_64 package) prior to subroutine "ParseOptions" that has nothing to do with the problem

would be great if you instead tell us the name of the distro, package, file and subroutine would be helpful... so we can compare the files

**Comment by CendioOssman** [comment] 2017-10-25 08:32
I was referring to `master`. So these lines:

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver#L760-L772

**Comment by atesin** [comment] 2017-10-25 15:22
yes mine has these lines too ... but maybe because previous lines 740-743 that exists immediately when pid file not found is that this check never comes

for some reason sometimes when server crashes pid files are deleted but lock files don't... check it with "killall -9 Xvnc"

**Comment by CendioOssman** [comment] 2017-10-30 08:12
That works perfectly here:

```
-bash-4.4$ vncserver 

New 'workstation:2 (tltest)' desktop is workstation:2

Starting applications specified in /local/home/tltest/.vnc/xstartup
Log file is /local/home/tltest/.vnc/workstation:2.log

-bash-4.4$ ls .vnc/
config             workstation:2.log  passwd
workstation:1.log  workstation:2.pid  xstartup
-bash-4.4$ killall -9 Xvnc
-bash-4.4$ ls .vnc/
config             workstation:2.log  passwd
workstation:1.log  workstation:2.pid  xstartup
-bash-4.4$ vncserver -kill :2
Killing Xvnc process ID 28050
Xvnc process ID 28050 already killed
Xvnc did not appear to shut down cleanly. Removing /tmp/.X11-unix/X2
Xvnc did not appear to shut down cleanly. Removing /tmp/.X2-lock
```

**Comment by atesin** [comment] 2017-10-31 21:00
mine says....

[root@coloso ~]# netstat -ntpl
tcp        0      0 0.0.0.0:5902            0.0.0.0:*               LISTEN      1201/Xvnc
...

[root@coloso ~]# cd .vnc/
[root@coloso .vnc]# ll -a
-rw-r--r--   1 root root 1366 oct 30 02:25 coloso:2.log
-rw-r--r--   1 root root    5 oct 30 02:25 coloso:2.pid
-rw-r--r--   1 root root  332 oct  4 02:21 config
-rw-------.  1 root root    8 oct  8  2016 passwd
-rwxr-xr-x   1 root root  179 oct 20 11:30 xstartup

[root@coloso .vnc]# ll -a /tmp/
drwxrwxrwt.  2 root   root       4096 oct 30 02:25 .X11-unix
-r--r--r--   1 root   root         11 oct 30 02:25 .X2-lock
...

[root@coloso .vnc]# ll -a /tmp/.X11-unix/
srwxrwxrwx   1 root root    0 oct 30 02:25 X2

[root@coloso .vnc]# killall -9 Xvnc

[root@coloso .vnc]# ll -a
-rw-r--r--   1 root root 2485 oct 31 17:55 coloso:2.log
-rw-r--r--   1 root root  332 oct  4 02:21 config
-rw-------.  1 root root    8 oct  8  2016 passwd
-rwxr-xr-x   1 root root  179 oct 20 11:30 xstartup

[root@coloso .vnc]# ll -a /tmp/
drwxrwxrwt.  2 root   root       4096 oct 30 02:25 .X11-unix
-r--r--r--   1 root   root         11 oct 30 02:25 .X2-lock

[root@coloso .vnc]# ll -a /tmp/.X11-unix/
srwxrwxrwx   1 root root    0 oct 30 02:25 X2

[root@coloso .vnc]# vncserver -kill :2

Can't find file /root/.vnc/coloso:2.pid
You'll have to kill the Xvnc process manually

[root@coloso .vnc]# ll -a /tmp/
drwxrwxrwt.  2 root   root       4096 oct 30 02:25 .X11-unix
-r--r--r--   1 root   root         11 oct 30 02:25 .X2-lock

[root@coloso .vnc]# ll -a /tmp/.X11-unix/
srwxrwxrwx   1 root root    0 oct 30 02:25 X2

**Comment by CendioOssman** [comment] 2017-11-02 13:40
I noticed the `vncserver` invocation is missing in your output though. How did you start it? Perhaps there is a difference there.

**Comment by atesin** [comment] 2017-11-02 15:10
vncserver invocation to start some display is ommited, but after this it shifts to another display because it thinks current is busy due lock files .. but invocation to kill some display is mentioned, what it is supposed to clean unused lock files before

i used stock systemd script, slighty modified to delete lock files before because default wasn't enough when linux server crashed

[Unit]
Description=Remote desktop service (VNC)
After=syslog.target network.target

[Service]
Type=forking
# Clean any existing files in /tmp/.X11-unix environment before, added by me
ExecStartPre=-/usr/bin/rm /tmp/.X2-lock /tmp/.X11-unix/X2
ExecStartPre=/bin/sh -c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
ExecStart=/usr/sbin/runuser -l root -c "/usr/bin/vncserver %i -geometry 1280x720 -depth 16 -nolisten tcp"

**Comment by CendioOssman** [comment] 2017-11-02 15:50
Hmm... I wonder if systemd somehow figures out where the pid file is and removes it. Could you try starting `vncserver` by hand instead of through systemd?

**Comment by atesin** [comment] 2017-11-03 02:46
before test i had commented the line on systemd unit conf that deletes lock files

```
[root@coloso system]# netstat -ntpl
tcp        0      0 0.0.0.0:5902            0.0.0.0:*               LISTEN      8858/Xvnc
...

[root@coloso system]# killall -9 Xvnc
[root@coloso system]# ll -a /tmp
-r--r--r--   1 root   root          11 oct 31 18:13 .X2-lock
...

[root@coloso system]# systemctl start vncserver@:2
Job for vncserver@:2.service failed because a configured resource limit was exceeded. See "systemctl status vncserver@:2.service" and "journalctl -xe" for details.
[root@coloso system]# netstat -ntpl
tcp        0      0 0.0.0.0:5901            0.0.0.0:*               LISTEN      62138/Xvnc
...

[root@coloso system]# journalctl -xe
nov 02 23:44:40 coloso runuser[62116]: Warning: coloso:2 is taken because of /tmp/.X2-lock
nov 02 23:44:40 coloso runuser[62116]: Remove this file if there is no X server coloso:2
nov 02 23:44:40 coloso runuser[62116]: A VNC server is already running as :2
nov 02 23:44:43 coloso runuser[62116]: New 'coloso:1 (root)' desktop is coloso:1
nov 02 23:44:43 coloso runuser[62116]: Starting applications specified in /root/.vnc/xstartup
nov 02 23:44:43 coloso runuser[62116]: Log file is /root/.vnc/coloso:1.log
nov 02 23:44:43 coloso runuser[62116]: pam_unix(runuser-l:session): session closed for user root
nov 02 23:44:43 coloso systemd[1]: PID file /root/.vnc/coloso:2.pid not readable (yet?) after start.
nov 02 23:44:43 coloso systemd[1]: Failed to start Remote desktop service (VNC).
-- Subject: Unit vncserver@:2.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit vncserver@:2.service has failed.
--
-- The result is failed.
nov 02 23:44:43 coloso systemd[1]: Unit vncserver@:2.service entered failed state.
nov 02 23:44:43 coloso systemd[1]: vncserver@:2.service failed.
...
```

**Comment by CendioOssman** [comment] 2017-11-06 14:30
I'm talking about the pid file now, not the lock files. Please start `vncserver` without systemd so we can see how that behaves on your system.

**Comment by atesin** [comment] 2017-11-06 19:30
i am not clear about the tests you want i will do


i realized "killall -9 Xvnc" deletes pid files, but not lock files (centos) .. looking the code, i think the script exits at once when no pid file found

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver#L740-L743
```
    if (! -r $pidFile) {
	die "\nCan't find file $pidFile\n".
	    "You'll have to kill the Xvnc process manually\n\n";
}
```

... skiping later code that handles lock files

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver#L749-L773
```
    if (kill 0, $pid) {
...
    } else {
	warn "Xvnc process ID $pid already killed\n";
	$opt{'-kill'} =~ s/://;
...
```

**Comment by kim0** [comment] 2018-07-25 10:04
I was facing a similar situation, where I ask systemd to always restart vncserver if it crashes. Somehow, a single user ended up filling up all sessions from :1 to :99 !! This happened over & over on multiple servers, whenever our NFS homes where not functioning correctly.

To be precise, this line as the first ExecStartPre seems to help (adding for others to find)
ExecStartPre=-/usr/bin/rm -f /tmp/.X%i-lock /tmp/.X11-unix/X%i

**Comment by atesin** [comment] 2018-07-26 03:52
@CendioOssman : 
is also clear for me that there is a design flaw in the script, maybe the clue i mentioned before could help to fix it (when no pid file found, script exits immediately and dont continue checking for lock files to clean)

**Comment by CendioOssman** [comment] 2019-01-11 14:31
This seems to be the result of some modified `vncserver` and not ours, so closing.

**Closed by CendioOssman** 2019-01-11 14:31 UTC

**Comment by kim0** [comment] 2019-01-15 22:04
I don't really like the tone of some of the comments here. @CendioOssman is not obliged to find or fix any bugs that exist and we should be thankful for his contributions! That said, the bug I've opened in #781 is indeed quite annoying. Although, I'd prefer to get it fixed using the new systemd integration code. That looks like it will be a more robust solution anyway! Really hoping that new code can land in the next release, which I'm hoping is a few months away. Thanks

**Comment by atesin** [comment] 2019-01-16 22:37
well sorry... after published i noted it sounds rude... i edited it, i dont want somebody feel offended

btw the issue stills persist

**Comment by kim0** [comment] 2019-01-17 00:01
Check my bug report. In my case I was using redhat RPM. While the official
one is on bintray. Try that one and see if you can reproduce it.

Thanks!

**Comment by haxj** [comment] 2019-08-21 10:29
The problem is in the vncserver' systemd service file:
```
# /etc/systemd/system/vncserver@.service

# Clean any existing files in /tmp/.X11-unix environment
ExecStartPre=/bin/sh -c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
ExecStart=/usr/sbin/runuser -l <USER> -c "/usr/bin/vncserver %i -geometry 1920x1017"
PIDFile=/home/<USER>/.vnc/%H%i.pid
ExecStop=/bin/sh -c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
```

The pre-start and stop command are executed as root and look for .pid file in /root/.vnc/ while the pid file is in /home/<USER>/.vnc/. When no .pid file is found, it doesn't clear the lock files.

A workaround without explicitly clearing the lock files:
```
# /etc/systemd/system/vncserver@.service

# Clean any existing files in /tmp/.X11-unix environment
ExecStartPre=/usr/sbin/runuser -l <USER>-c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
ExecStart=/usr/sbin/runuser -l <USER> -c "/usr/bin/vncserver %i -geometry 1920x1017"
PIDFile=/home/<USER>/.vnc/%H%i.pid
ExecStop=/usr/sbin/runuser -l <USER>-c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
```

**Comment by zhuzhucui** [comment] 2021-07-07 04:14
not work
