### ISSUE TITLE
How does TigerVNC server on Windows creates/connects to the built-in virtual display of a VM that is headless?

### ISSUE THREAD

**Issue by philippemnoel** [TigerVNC/tigervnc#940] opened 2020-01-11 21:38 UTC
I'm using TigerVNC to connect to an AWS Windows Server VM and when it does it indicates in the Nvidia Control Panel "DCV Display". When I use RDP, no display is shown.

I'm trying to understand how TigerVNC connects to the built-in virtual display of a headless VM. I see there's /common/region.c which seems to create something analogous to an X11 display, is that it? Could someone please explain to me which files are called to generate/connect to the virtual display so the code works on a headless server? I would really appreciate guidance, I've been looking at the code for a while but still not quite sure how it goes down.

Philippe

**Comment by CendioOssman** [comment] 2020-01-13 08:17
Duplicate of discussion on mailing list. Please see there.

**Closed by CendioOssman** 2020-01-13 08:17 UTC
