### ISSUE TITLE
-nocursor still shows cursor?

### ISSUE THREAD

**Issue by SoniEx2** [TigerVNC/tigervnc#1879] opened 2024-11-24 14:37 UTC
**Describe the bug**
when launching with -nocursor, the cursor is still visible.

**To Reproduce**
1. launch with -nocursor
2. connect with a client, e.g. obs-vnc

**Expected behavior**
there should not be a cursor

**Screenshots**

**Client (please complete the following information):**
 - OS: arch linux
 - VNC client: obs-vnc
 - VNC client version: 0.5.0
 - Client downloaded from: AUR

**Server (please complete the following information):**
 - OS: arch linux
 - VNC server: tigervnc
 - VNC server version: 1.14.0 and later
 - Server downloaded from: arch linux
 - Server was started using: xinit

**Additional context**
it correctly hides the cursor on 1.13.1 so that's what we downgraded to for now

**Comment by CendioOssman** [comment] 2024-11-25 14:52
Thanks for your report!

I can reproduce the issue here as well. It is strange, though, because the cursor code has not changed in many years.

I think it might be a subtle side effect of 662676e3b8bf06d365e4906c1979e188125906da.

**Comment by CendioOssman** [comment] 2024-11-26 09:25
Fixed in 1cc5bb27701684d196ae5b35208e573fb0a0af2a.

**Closed by CendioOssman** 2024-11-26 09:25 UTC
Labels: bug
