### ISSUE TITLE
Cannot determine user of subject - headless VNC

### ISSUE THREAD

**Issue by Bun-Bun** [TigerVNC/tigervnc#581] opened 2018-01-14 19:40 UTC
I have a fresh install of Fedora 27 XFCE inside of a Hyper-V VM. I plan to use this 100% remotely hence the headless VNC. I have installed tigervnc-server and configured it to run on :0, done a "systemctl set-default multi-user.target" and opened up the vnc-service on firewall. 

The problem arrises when connecting over with tightVNC. Upon starting the session I am presented with an error box saying "XFCE PolicyKit Agent" and "GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Cannot determine user of subject" and I click close to make it go away. Note that I am not asked to log in the desktop for my user is already up.

But anything that requires elevation privilege does not work now. I don't get errors, just nothing happens when I try to open say gparted or install something with the GUI software manager. Is there additional steps I need to take with VNC config to get the user working correctly with PolicyKit and VNC?

I have tried disabling PolicyKit on startup and adding a policy

Identity=unix-group:wheel
Action=*
ResultActive=yes

and still can't launch anything requiring elevation. 

My xstartup in ~/.vnc/ contains 

```
#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
exec /etc/X11/xinit/xinitrc
```

I feel like something is not starting up correctly. Or this is some permissions issue with remote vs local...

**Comment by CendioOssman** [comment] 2018-01-16 10:06
Yeah, it does sound like an incorrect startup somehow. My first guess would be the same problem we've seen with Red Hat's packaging and GNOME 3. Which version of Red Hat's TigerVNC package do you have?

**Comment by Bun-Bun** [comment] 2018-01-16 19:07
1.8.0-5.fc27

I tried with Gnome3 as well and just get a black screen. In the mean  time I'm using the built in screen sharing with Gnome3 but I would prefer to use xfce and vncserver headless.

**Comment by CendioOssman** [comment] 2018-01-22 14:29
It should be fixed in that version.

How are you starting the server? Does it work if you use the `vncserver` command from a terminal?

**Comment by feuerbach** [comment] 2018-01-28 13:03
I have the same problem with tigervnc-server-1.8.0-5.fc27. I tried tigervnc's default x startup script as well as putting

```
exec xfce4-session
```

and 

```
exec lxsession
```

into `~/.vnc/xstartup`.

Starting the server with `vncserver -SecurityTypes None` (it is exposed over a vpn).

**Comment by CendioOssman** [comment] 2018-02-27 14:39
Have you talked to the Xfce people? I think they'll have to answer what they feel is missing from the session.

**Comment by eckirchn** [comment] 2018-05-13 20:52
I have the same issue after an upgrade to Fedora 27

**Comment by CendioOssman** [comment] 2018-05-14 14:50
I'm afraid there I cannot find anything really pointing to a bug in TigerVNC for this one. It seems like Xfce and PolicyKit aren't playing nice under some circumstances. I'm afraid you'll have to continue the discussion with one of those projects.

**Closed by CendioOssman** 2018-05-14 14:50 UTC

**Comment by not-a-user** [comment] 2018-06-20 15:59
I have no clue what the root cause is and its probably not a vnc issue, but if you have the same problem, there is a workaround described here: https://forums.fedoraforum.org/showthread.php?316905-PolicyKit-failed-over-headless-VNC&p=1809280#post1809280
