### ISSUE TITLE
Scroll_Lock blocked for other VNC clients

### ISSUE THREAD

**Issue by stefvanvlierberghe** [TigerVNC/tigervnc#865] opened 2019-08-27 16:30 UTC
We were using the Scroll-Lock as an Emacs shortcut key and with 19.0 this no longer works, i.e. xev no longer reacts when pressing this key, presumably because of this new feature.

Ideally there would be an option to pass all these keys to the vnc server as such.

We considered alternatively to stay on the 1.8.0 (included rhel7) but that won't work in the long term.

**Comment by CendioOssman** [comment] 2019-10-04 11:24
Scroll lock should not be affected in that way because of this new feature. So I'd like to debug this a bit more.

Have you determined if the issue is with the client or the server?

Could you enable debug logging (`-Log *:stderr:100`) and see what it prints when pressing the Scroll lock key?

**Comment by stefvanvlierberghe** [comment] 2019-10-04 11:48
Hi Pierre,

Thanks for looking into this issue.

It is an issue with the server, I compared :
Xvnc TigerVNC 1.9.0 has the issue, the 1.8.0 does not have the issue.

The log file shows the server ignores the event :

VNCSConnST:  Key released: 0xff14 / 0x0
VNCSConnST:  Ignoring lock key (e.g. caps lock)
VNCSConnST:  Key pressed: 0xff14 / 0x0
VNCSConnST:  Ignoring lock key (e.g. caps lock)
VNCSConnST:  Key released: 0xff14 / 0x0
VNCSConnST:  Ignoring lock key (e.g. caps lock)
VNCSConnST:  Key pressed: 0xff14 / 0x0
VNCSConnST:  Ignoring lock key (e.g. caps lock)
VNCSConnST:  Key released: 0xff14 / 0x0
VNCSConnST:  Ignoring lock key (e.g. caps lock)
VNCSConnST:  Key pressed: 0xff14 / 0x0
VNCSConnST:  Ignoring lock key (e.g. caps lock)
VNCSConnST:  Key released: 0xff14 / 0x0
VNCSConnST:  Ignoring lock key (e.g. caps lock)
VNCSConnST:  Key pressed: 0xff14 / 0x0
VNCSConnST:  Ignoring lock key (e.g. caps lock)
VNCSConnST:  Key released: 0xff14 / 0x0
VNCSConnST:  Ignoring lock key (e.g. caps lock)


There seems to be a confusion between keys, the above happens when I press “Scroll Lock”.

When I press the Caps Lock key that one does not get ignored :

VNCSConnST:  Key released: 0xffe5 / 0x0
Input:       keycode 66 up
VNCSConnST:  Key pressed: 0xffe5 / 0x0
Input:       keycode 66 down
VNCSConnST:  Key released: 0xffe5 / 0x0
Input:       keycode 66 up
VNCSConnST:  Key pressed: 0xffe5 / 0x0
Input:       keycode 66 down
VNCSConnST:  Key released: 0xffe5 / 0x0
Input:       keycode 66 up

I also see these events in the xevent log, so there seems to be a confusion between caps and scroll lock keys.

This is what the vncserver returns for xmodmap :

vvl@dhws029> xmodmap -pke | grep -i -e caps -e scroll
keycode  66 = Caps_Lock NoSymbol Caps_Lock
keycode  78 = Scroll_Lock NoSymbol Scroll_Lock
keycode 185 = XF86ScrollUp NoSymbol XF86ScrollUp
keycode 186 = XF86ScrollDown NoSymbol XF86ScrollDown

And this xkbmap :

vvl@dhws029> setxkbmap -print
xkb_keymap {
                xkb_keycodes  { include "evdev+aliases(qwerty)"              };
                xkb_types     { include "complete"             };
                xkb_compat    { include "complete"         };
                xkb_symbols   { include "pc+us+inet(evdev)"       };
                xkb_geometry  { include "pc(pc105)"       };
};

But the 1.8.0 returns me the same output for these commands.

Hope this helps.

All the best,
Stef

**Comment by CendioOssman** [comment] 2019-10-04 14:18
Hmm... What client are you using? The warning you are seeing should only trigger in the compatibility code.

**Comment by stefvanvlierberghe** [comment] 2019-10-04 14:53
We were always using the 1.8.0 viewer, so the issue only exists in the compatibility mode.
Our servers always run on Linux and on Windows PCs people use realvnc 6.19.325 viewers to look at the servers, in which case we also lose the scroll lock.
I confirm that 1.9.0 viewer to 1.9.0 server does not have the issue.
Thanks for identifying the problem, if this is hard to fix then I guess we will just wait until newer versions become available everywhere.
All the best,
Stef

**Comment by CendioOssman** [comment] 2019-10-11 07:31
That explains things a bit at least. Thanks.

I'll try to find some time to look at it more in detail and see what can be done. We would like to have good support for all clients out of box.

**Comment by CendioOssman** [comment] 2019-10-14 09:39
Alright, so some more clarity to this.

In the old code Scroll Lock would work *sometimes*. It was dependent on if XK_ScrollLock was set up as a modifier or not. If it isn't then it isn't really a lock key and so it got passed through.

In the new code we unfortunately cannot tell if it is configured as a lock key or not, so we have to assume it is and drop it.

I'm not sure the old way was better since it was not very predictable for most users.

We could consider always letting lock keys through. The problem there is that things can get out of sync and we'll have users confused that the scroll lock LED is on, but applications behave like it is off.

**Comment by stefvanvlierberghe** [comment] 2019-10-14 16:53
Thanks for the follow up Pierre.

Perhaps the cleanest solution is to provide an option so that people using this key in their application can have it passed through, while people using it as a lock key can benefit from the new feature.

All the best.

**Comment by samhed** [comment] 2019-10-17 19:11
Adding even more settings doesn't feel great imo.

I'm guessing your users are too familiar with scroll lock as this emacs hotkey? Or why can't you just change it?

**Comment by stefvanvlierberghe** [comment] 2019-12-31 14:44
Yes indeed, many developer are using emacs hotkeys and all normal|shift|control|alt combinations of “top row” keys are mapped to emacs functions.

I don’t understand the issue with more settings, people who won’t use this setting won’t be impacted.
Can you be more specific about why settings don’t feel great to you ?

Could also be controlled via some environment variable if you prefer, e.g. :
$ VNC_PLEASE_DONT_HANDLE_SCROLL_LOCK=true vncserver

All the best,
Stef

**Comment by samhed** [comment] 2020-01-02 09:15
People who won't use the setting will be affected by an increasingly complex interface. The fewer settings, the better.

**Comment by CendioOssman** [comment] 2020-01-02 10:57
That is part of it, yes. But a big factor is also that we developer need to maintain all settings. So we want to make sure we solve the issue for as many users as possible. A configuration option will be difficult to understand and use for many users.

Scroll Lock is a bit different from the other lock keys though, so I think we can try letting it through. If we get reports of that causing issues then we can revisit the topic.

I'm not at my normal workstation right now though, so I can't make the change right away.

**Comment by stefvanvlierberghe** [comment] 2020-01-02 11:01
Happy 2020.
Thanks Pierre, that would be perfect for us.
Don’t hurry ☺.
All the best,
Stef

**Comment by CendioOssman** [comment] 2020-01-03 12:49
Should be fixed in 81e114f29f007c689a41ca2bb72f314d50898381.

**Closed by CendioOssman** 2020-01-03 12:49 UTC
Labels: bug
