### ISSUE TITLE
Mouse problem on Ati chipset using xorg module

### ISSUE THREAD

**Issue by elsupergomez** [TigerVNC/tigervnc#309] opened 2016-05-11 11:28 UTC
The real cursor position is dissociated with the drawled mouse cursor on the screen.
Is very difficult to use mouse to click or point on the screen.

I use tigervnc-module for vnc remote on many workstation configured with standard options
When the module is load with basic configuration from example config file cause this bug

If I uninstall tigervnc-server-module or comment the file configuration in /etc/X11/xorg.conf.d/ the pointer work fine.

It seam to be a problem with AMD video chipset.
I tested on various hardware and work fine on nvidia and intel

Using Fedora 22 work fine.
Xorg 1.7
Ati driver 7.5.0 open source
tigervnc 1.6.0

Using Fedora 23 or newer happens this problem
Xorg 1.18.3
Ati driver 7.6.1 open souce
tigervnc 1.6.0

I open bug in Fedora bugzilla to:

https://bugzilla.redhat.com/show_bug.cgi?id=1334927
https://bugzilla.redhat.com/show_bug.cgi?id=1278949

**Comment by CendioOssman** [comment] 2016-05-11 11:40
It does indeed sound like the problem is somehow related to the radeon driver. So please file a bug report with them. I'll close this issue for now. If they find something indicating that the problem is in TigerVNC rather than radeon, then we can re-open the issue.

**Closed by CendioOssman** 2016-05-11 11:40 UTC

**Comment by elsupergomez** [comment] 2016-06-30 14:23
I update to Ati driver 7.7.0 open souce and work fine.
Thanks.
