### ISSUE TITLE
Intense drawing artifacts on GNOME Wayland in vncviewer

### ISSUE THREAD

**Issue by eomanis** [TigerVNC/tigervnc#1663] opened 2023-08-29 20:46 UTC
**Describe the bug**
The FLTK VNC viewer is unusable because drawing is glitching intensely.

Basically, on every surface update the picture gets brighter and brighter, until almost everything is white.
See attached video.

The following behaviors can be observed:
 - Entering the GNOME Shell's overview mode partly resets the drawing
 - The Java VNC viewer is not affected, and neither is Remmina
 - Another FLTK application, in this case the `dillo` web browser in version 3.0.5, is not affected
 - Screenshots with the GNOME Shell built-in screenshot functionality yield pictures where the drawing surface of the VNC viewer window is transparency
 - In screen recordings with the GNOME Shell built-in screenshot functionality the VNC viewer window looks as it should, i.e. does not show the glitchy drawing; same goes for the preview in OBS when capturing the respective screen with Pipewire

**To Reproduce**
1. Open the native (FLTK) VNC viewer in a GNOME Wayland session
2. Connect to a VNC server
3. Note the drawing artifacts described above

**Expected behavior**
The view of the VNC server's desktop should be painted without glitches.

**Screenshots**
Smartphone video recording showing the drawing glitches; the VNC server is showing a website in fullscreen mode in Firefox:
https://github.com/TigerVNC/tigervnc/assets/5933155/e6bc077a-d172-4a5c-ba26-9e66ef511cc4

**Client (please complete the following information):**
 - OS: Arch Linux
 - VNC client: TigerVNC, `/usr/bin/vncviewer`
 - VNC client version: `1.13.1-2`
 - Client downloaded from: Arch Linux packages mirror, with the distribution's package manager `pacman`

**Server (please complete the following information):**
 - OS: Arch Linux
 - VNC server: TigerVNC, `/usr/bin/x0vncserver`
 - VNC server version: `1.13.1-2`
 - Server downloaded from: Arch Linux packages mirror, with the distribution's package manager `pacman`
 - Server was started using: `/usr/bin/x0vncserver -PasswordFile /home/theuser/.vnc/passwd -display :0`

**Additional context**
 - The other tested FLTK application `dillo` that does not show the glitch was built 2022-11-01, whereas the affected TigerVNC package was built 2023-08-10. Maybe this is a FLTK regression that happened between these builds.
 - GNOME Shell version 44.4 (`gnome-shell-1:44.4-1`)
 - Mesa 23.1.6 (`mesa-1:23.1.6-4`)
 - Graphics: AMD Radeon RX 480
 - Linux 6.4.12 (`linux-6.4.12.arch1-1`)

**Comment by vowstar** [comment] 2023-09-01 02:48
I also encountered the same problem，

## Screenshots

![2023-09-01_10-02](https://github.com/TigerVNC/tigervnc/assets/394260/8eaa6f0e-40b6-47ca-aea6-4cad65a0c2fa)

## Client (please complete the following information):

OS: Gentoo Linux x86_64
VNC client: TigerVNC, /usr/bin/vncviewer
VNC client version: 1.13.1
Client downloaded from: https://github.com/TigerVNC/tigervnc/archive/v1.13.1.tar.gz (and built by gentoo's ebuild from source)

## Server (please complete the following information):

OS: Gentoo Linux x86_64
VNC server: TigerVNC, /usr/bin/x0vncserver, via systemd
VNC server version: 1.13.1-2
Server downloaded from: https://github.com/TigerVNC/tigervnc/archive/v1.13.1.tar.gz (and built by gentoo's ebuild from source)
Server was started using: systemctl start vncserver@:1.service

## Additional context

GNOME Shell version 44.3
Mesa 23.2.0
Graphics: NVIDIA GeForce RTX 2080 Ti Rev. A
Linux 6.4.13-gentoo-x86_64

**Comment by samhed** [comment] 2023-09-01 13:56
Works well for me. I cannot reproduce on Fedora 38:

## Screenshots
![image](https://github.com/TigerVNC/tigervnc/assets/4117162/a129a383-5815-4d63-9e27-8cfdc831df13)

## Client:
OS: Fedora 38
VNC client: TigerVNC, /usr/bin/vncviewer
VNC client version: 1.13.1
Client downloaded from: Fedora System repository

## Server:
OS: RHEL 9
VNC server: TigerVNC, /usr/bin/x0vncserver
VNC server version: 1.13.1
Server downloaded from: https://sourceforge.net/projects/tigervnc/files/stable/1.13.1/
Server was started using: /usr/bin/x0vncserver -SecurityTypes None

## Additional context

GNOME Shell version 44.3
Mesa 23.1.6
Graphics: Intel Corporation CoffeeLake-S GT2 [UHD Graphics 630]
Linux 6.4.11-200.fc38.x86_64

**Comment by samhed** [comment] 2023-09-01 13:59
I also cannot reproduce with a vncviewer downloaded from [our sourceforge](https://sourceforge.net/projects/tigervnc/files/stable/1.13.1/) or with a TigerVNC vncviewer I built myself on Fedora.

**Comment by eomanis** [comment] 2023-09-01 14:28
@vowstar Your glitches look kind of different than the ones I get, also you could capture yours in a screenshot whereas I had to use external recording.

This, along with greater differences in the graphics subsystems, makes me suspect that there are two separate graphical problems, and this one may an Arch-specific issue since it is not reproducible on @samhed 's Fedora+Wayland(?)+Mesa+Intel. Or it could be specific to AMD graphics.

Anyone have Arch+Wayland+Mesa+AMD?
Or [OtherDistro]+Wayland+Mesa+AMD?

Anyway, I'll file an issue at the Arch bug tracker.

**Comment by paquiteau** [comment] 2023-09-03 14:11
Hello there, 
I am having the same issue.

I am running a Arch + Wayland(GNOME) + Mesa (1:23.1.6-4, updated on 2023-08-31) 
Hardware: Thinkpad T14 (Gen1), with AMD Ryzen 5 PRO 4650U  with integrated Radeon Graphics.

On a another laptop running Ubuntu 22.04 Wayland (GNOME) with AMD Radeon Graphics, everything works fine.

**Comment by samhed** [comment] 2023-09-06 12:40
So far, evidence seem to point towards Arch being the common denominator for the issue. From a comment on the arch issue tracker:

> graphical glitches like this are often mesa/driver/kernel related

With this in mind, I will go ahead and close this issue for now. We will reopen if needed.

**Closed by samhed** 2023-09-06 12:40 UTC

**Comment by eomanis** [comment] 2023-09-22 09:21
Works for me again with Arch package `xorg-xwayland-23.2.1-1`.
May have been [this issue](https://gitlab.freedesktop.org/xorg/xserver/-/issues/1575).

**Comment by vowstar** [comment] 2023-09-22 15:48
> Works for me again with Arch package `xorg-xwayland-23.2.1-1`. May have been [this issue](https://gitlab.freedesktop.org/xorg/xserver/-/issues/1575).

Works for me with ``gentoo::x11-base/xwayland-23.2.1``, may same issue.
