### ISSUE TITLE
SMsgWriter::writeFramebufferUpdateEnd: nRects out of sync

### ISSUE THREAD

**Issue by coolo** [TigerVNC/tigervnc#914] opened 2019-12-04 09:55 UTC
It's a little hard to explain how to reproduce it - as for http://open.qa we use a custom VNC client, that is basically written in perl and it sounds like you need it to reproduce. Our client only supports a small number of pseudo encodings and this seems to trigger the code path.

Basiscally what I see is https://github.com/TigerVNC/tigervnc/blob/master/common/rfb/EncodeManager.cxx#L343 having copied rects of 3 and then changed rects of 5, but the framebuffer update only contains 5 rects then and it's crashing and disconnects the client.

I can't see any fault in the client though.

**Comment by coolo** [comment] 2019-12-04 10:59
I forgot to mention that this is about Xvnc crashing

**Comment by samhed** [comment] 2019-12-05 09:33
Could you post the full stack trace you get when Xvnc crashes?

**Comment by Martchus** [comment] 2019-12-05 09:43
The latest version (1.10.0) hasn't been crashing. At least within my tests it even fact kept serving a simultaneously connected vncviewer client. Only our VNC client without support for the 'last rect' pseudo encoding is disconnected with the following error message:

```
 VNCSConnST:  closing 127.0.0.1::35822: SMsgWriter::writeFramebufferUpdateEnd:
              nRects out of sync
 EncodeManager: Framebuffer updates: 169
 EncodeManager:   ZRLE:
 EncodeManager:     Solid: 123 rects, 962.868 kpixels
 EncodeManager:            2.9043 KiB (1:648.02 ratio)
 EncodeManager:     Bitmap RLE: 226 rects, 544.684 kpixels
 EncodeManager:                 14.7705 KiB (1:72.2036 ratio)
 EncodeManager:     Indexed RLE: 7 rects, 200.878 kpixels
 EncodeManager:                  3.78516 KiB (1:103.674 ratio)
 EncodeManager:     Full Colour: 2 rects, 900 pixels
 EncodeManager:                  268 B (1:6.80597 ratio)
 EncodeManager:   Total: 358 rects, 1.70933 Mpixels
 EncodeManager:          21.7217 KiB (1:153.889 ratio)
 Connections: closed: 127.0.0.1::35822
 ComparingUpdateTracker: 1.24823 Mpixels in / 400.356 kpixels out
 ComparingUpdateTracker: (1:3.11781 ratio)
```

We could workaround the issue by implementing the 'last rect' pseudo encoding within our client. So that really makes the difference.

**Comment by samhed** [comment] 2019-12-08 18:17
Ok, the problem you're seeing is that you can't connect to the TigerVNC server unless you the client has support for LastRect. And with older versions of the TigerVNC it even crashed?

The RFB specification says that LastRect should be optional, so this should probably be looked further into.

**Comment by coolo** [comment] 2019-12-08 20:52
No, the crash is unrelated - I shouldn't have used that phrase. The problem is that Xvnc disconnects clients that do not support lastrect.

**Comment by CendioOssman** [comment] 2019-12-09 13:10
Let's have a look. We rarely test without LastRect support, so I'm not entirely surprised there might be bugs there.

Do you think you could put together a list of which encodings your client supports so we can try to reproduce it?

**Comment by coolo** [comment] 2019-12-09 13:20
```
    {
        num       => 0,
        name      => 'Raw',
        supported => 1,
    },
    {
        num       => 16,
        name      => 'ZRLE',
        supported => 1,
    },
    {
        num       => -223,
        name      => 'DesktopSize',
        supported => 1,
    },
    {
        num       => -257,
        name      => 'VNC_ENCODING_POINTER_TYPE_CHANGE',
        supported => 1,
    },
    {
        num       => -261,
        name      => 'VNC_ENCODING_LED_STATE',
        supported => 1,
    },
```

That's all we had (until we added last rect to avoid the problem)

**Comment by CendioOssman** [comment] 2019-12-09 13:32
I modified our client to only use those encodings, but I'm afraid I cannot reproduce the issue. :/

Do you do something specific to trigger this?

Can we easily test using your client perhaps?

**Comment by Martchus** [comment] 2019-12-09 13:58
> Do you do something specific to trigger this?

The issue occurred when the screen changed a lot. So for instance typing just a few letters within a terminal will *not* trigger it.

> Can we easily test using your client perhaps?

Our VNC client lives within that Perl module: https://github.com/os-autoinst/os-autoinst/blob/master/consoles/VNC.pm

So you could clone the repo and make use of it. @coolo said he could reproduce the issue using the following Perl script:

```
use consoles::VNC;
use cv;

cv::init();
require tinycv;

my $vnc = consoles::VNC->new({hostname => 'localhost', port => 5901});
$vnc->login(10);

while (1) {
  $vnc->update_framebuffer();
  $vnc->send_update_request();
  $vnc->_framebuffer->write('test.new.ppm') if $vnc->_framebuffer;
  rename('test.new.ppm', 'test.ppm');
}
```

Unfortunately you need to follow the build instructions to build some native parts before. And of course you need to revert my commit for 'LastRect' support.

**Comment by CendioOssman** [comment] 2019-12-09 14:25
I was able to reproduce this now and the fix is in 86f4f47365f61ccf6104973317af227d6166d7a0. Thanks for your report!

**Closed by CendioOssman** 2019-12-09 14:25 UTC

**Comment by Martchus** [comment] 2019-12-09 14:34
Thanks.

Considering the branching in the code the absence of `CopyRect` and `LastRect` support at the same time is problematic. So we should be on the safe side with only `LastRect` support in the client, right?

**Comment by CendioOssman** [comment] 2019-12-09 16:05
That looks sufficient, yes.
