### ISSUE TITLE
Java client 1.11.0 has strange black outline around mouse cursor

### ISSUE THREAD

**Issue by fnJeff** [TigerVNC/tigervnc#1216] opened 2021-03-09 14:39 UTC
**Describe the bug**
Mouse cursor has a strange black outline in this version of the java client that was not there in 1.10.1.

**To Reproduce**
Hopefully it is obvious, but it may be related to the window manager, etc.  I am using KDE, but would need to know exactly what information would help you.

**Expected behavior**
No black outline around mouse cursors.

**Screenshots**
Java client 1.11.0
![image](https://user-images.githubusercontent.com/31246517/110485562-16515c00-80ec-11eb-9d3a-7cc7014b71ec.png)

Java client 1.10.1
![image](https://user-images.githubusercontent.com/31246517/110485722-3aad3880-80ec-11eb-88fc-9d1fc034c4f4.png)

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNC java
 - VNC client version: 1.11.0
 - Client downloaded from: github release

**Server (please complete the following information):**
 - OS: Linux xxxxx 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - VNC server: Not sure, IT managed
 - VNC server version: Not sure, IT managed
 - Server downloaded from: Not sure, IT managed
 - Server was started using: Not sure, IT managed

**Comment by bphinz** [comment] 2021-03-09 15:04
That "border" is an artifact of alpha cursor support but what's interesting
is that on my screen it does not look like the image you posted (I just
have a slight border that looks like an intentional drop shadow).  I wonder
if it's resolution dependent?  What screen res are you using on the
remote/local sides

**Comment by fnJeff** [comment] 2021-03-09 15:40
Interesting, and unfortunate that you don't see the same thing.  More
annoying to debug.

Does this connection info give you what you need to know?  If not, please
just tell me exactly what I need to do to get the info you need.

[image: image.png]

fnJeff

**Comment by bphinz** [comment] 2021-03-09 16:50
Looks like you've uncovered a bug.  Alpha cursors are not supported by the JRE on Windows (they have that same chunky shadow), and so they are excluded from the list of supported encodings.  However, VMware cursors look identical and for some reason the server/client is selecting that encoding.  I'll figure out why and correct that but even the cursor that I see looks better now, so thanks for opening this issue.  I'll try to get the selection order resolved in the next day or two.

**Comment by fnJeff** [comment] 2021-03-09 17:07
Excellent, glad you already identified the issue.

Honestly it was completely by accident while I was creating the other issue.

**Comment by bphinz** [comment] 2021-03-09 17:48
@CendioOssman - it looks like on line 422 in common/rfb/SMsgWriter.cxx, the server will always prefer pseudoEncodingVMwareCursor over pseudoEncodingCursor or pseudoEncodingXCursor if the client supports it, regardless of whether or not VMware has anything to do with either.  Do you know why that is, or under what circumstances it's actually necessary/appropriate to use that encoding?

**Comment by CendioOssman** [comment] 2021-03-11 15:12
I don't quite understand the question. Yes, it prefers formats that support alpha over those that don't since that provides a more accurate representation of the cursor. And it won't send it to a client that doesn't support it. So I don't understand what the issue is?

**Comment by bphinz** [comment] 2021-03-11 15:14
No real issue, I just wanted to make sure that was the intended behavior.
I'm not familiar with the VMware cursor encoding and where it's used

**Comment by bphinz** [comment] 2021-03-12 00:34
Fixed in 2be74db

**Closed by bphinz** 2021-03-12 00:34 UTC

**Comment by fnJeff** [comment] 2021-03-12 08:29
Awesome, thanks Brian.

Any idea when you plan for the next stable release with this fix?
