### ISSUE TITLE
Full screen issue with new beta on OsX

### ISSUE THREAD

**Issue by RobyB** [TigerVNC/tigervnc#1332] opened 2021-09-13 10:18 UTC
I tried out the new beta on my mac:
MacBook Pro (13-inch, 2017) running macOS Mojave 10.14.6
---
If i go full screen on my external monitor (independently of how i choose the monitor setting in Options menu) what happens is that i have no way to get back to other OsX apps (running on different displays) in any way.
With previous version i just had to click on any OsX app and focus would go to OsX and there i could switch to other apps (including full screen TigerVnc) clicking on Alt+Tab.
With this new version this is no longer possible as, apparently, once going to full screen, TigerVnc occupies all three monitors just for the active app in the top menu (independent of all possible combinations of settings for full screen in Option menu) and therefore if i click on an OsX app this one will gain focus for a very short period of time and will switch back to TigerVnc almost immediately (< 1 second).
Needless to say that this "feature" makes full screen mode (even on a single monitor) completely useless and therefore i cannot use TigerVnc at all.
Only way to switch between apps is to exit Full Screen mode and then everything works as expected.

With current stable version this does not happen, forced to stick to that one

**Comment by CendioOssman** [comment] 2021-09-13 10:22
Hmm.. We didn't see any such issues when testing, but I'll have to have another look.

For clarity, do you think you could share some screenshots? Just to make sure we don't misunderstand what you're seeing.

**Comment by RobyB** [comment] 2021-09-13 12:20
HI,
   i will try to explain better and add two screen shots.
My setup is laptop with display L + two external monitors M1 and M2.
The layout is:
M1 - M2 - L
I have usually TigerVnc running on M1 in full screen. I go to full screen opening options menu and pressing f key.
If i select TigerVnc app everything in there works fine, but if i want to switch to my OsX apps (running on M2 and L) i cannot.
If i click on any OsX app, or empty desktop (as i usually do with current version of TigerVnc) the focus stays on TigerVnc.
The reason for that being, i suppose, that the TigerVnc menubar is expanded to cover all three displays, even if the app is using only one screen.
This can be seen in the first picture that depicts M2, with TigerVnc running in full screen on M1.
Same thing happens on my laptop screen L.
Therefore the only way for me to switch back to OsX is to  exit TigerVnc from full screen, and then i can regain control over OsX apps just clicking on one of them or on an empty desktop.
This happens regardless of the Screen settings that i set in VNC viewer connection options.
In the second picture i show one of my settings, but neither combination works for me.
I tried enabling/disabling full-screen, selecting any combination of Use current monitor, use all monitors, use selected monitor(s) even selecting none, just one, two out of three or all three. 
Hope this clarifies things a little bit more
![TigerVncMenu](https://user-images.githubusercontent.com/4759355/133082286-b41987fe-d32f-4fab-9ec0-27c5a8ce3039.png)
![TigerVncOptions](https://user-images.githubusercontent.com/4759355/133082300-eadc6c25-cdc6-44ce-8242-801569936fcc.png)

**Comment by CendioOssman** [comment] 2021-09-13 13:23
Thanks. I can reproduce the issue here on macOS 11. I can see it with both the official beta builds, as well as my own builds. So this seems to be some general bug.

I'll have to dig around a bit and get back to you.

**Comment by samhed** [comment] 2021-09-16 12:33
This a regression caused by commit 2289342de7222e4ff2483eae95bb9898830e6097

**Comment by samhed** [comment] 2021-10-05 09:24
This is fixed now.

**Closed** 2021-10-05 09:23 UTC
Labels: bug
