### ISSUE TITLE
non-english symbols and emoji

### ISSUE THREAD

**Issue by ricary37** [TigerVNC/tigervnc#339] opened 2016-08-04 16:14 UTC
I connect to my debian 8 tigervnc server via tigervnc client (or bvnc client for android).
not all symbols of non-english keyboard can be sent (for example "ф", "щ").
also emoji symbols can not be sent.

**Comment by CendioOssman** [comment] 2016-08-15 14:11
Those should work fine. What platform are you running the TigerVNC client on? And how are you starting the server?

**Comment by ricary37** [comment] 2016-08-15 14:32
Windows 8.1 x64 Enterprise

**Comment by ricary37** [comment] 2016-08-16 09:43
How I start the server: I added the strings below into /etc/rc.local :
export HOME=/root
vncserver -SecurityTypes=None,VncAuth -geometry 768x900 -dpi 96

**Comment by CendioOssman** [comment] 2016-08-18 14:43
I'm afraid I'm unable to reproduce that issue. Those keys work fine for me.

Do other non-latin characters work? Are you using the standard Windows Russian keyboard layout?

**Comment by ricary37** [comment] 2016-08-18 15:50
this helped:
setxkbmap -symbols "pc+us+us(intl):2" -print | sed -n '/xkb_keymap {/,$p' | xkbcomp - $DISPLAY

**Comment by CendioOssman** [comment] 2016-08-19 08:41
In that case it sounds like you are being hit by #93. I'll close this issue as a duplicate for now.

**Closed by CendioOssman** 2016-08-19 08:41 UTC
