### ISSUE TITLE
TigerVNC server creating corrupt jpeg encode

### ISSUE THREAD

**Issue by brettwilliams** [TigerVNC/tigervnc#218] opened 2015-10-13 22:57 UTC
I am currently getting corrupt jpegs when using the TigerVNC server.  Problem found when using the TurboVNC viewer.

Client:
Mac OS/X 10.9.5
TurboVNC Viewer 2.0 (20150714) (Java Hotspot 1.6.0_65 x86_64)

Server:
CentOS 6.5
tigerVNC 1.5.0-21
libjpeg-turbo-official-1.4.2-20150921

This happens when I use a particular piece of commercial software.  TurboVNC errors out.  Other clients I have tried do not have an error with this application, but I was not using jpeg encoding with them.

In working with the TurboVNC developers, I've managed to capture an example of this corrupted jpeg.  The file is corrupt and can't be decoded using libjpeg standalone.  This seems to indicate a server side issue, or a bug in the encoder itself.

error0.jpg

**Comment by brettwilliams** [comment] 2015-10-13 22:58
Attempting to attach jpeg again.
![error0](https://cloud.githubusercontent.com/assets/752638/10470590/969f9cd6-71cb-11e5-8b64-3252b879dda2.jpg)

**Comment by CendioOssman** [comment] 2015-10-14 06:56
Have you tried our client? Or TightVNC? Both support JPEG.

What is TurboVNC erroring out on? The JPEG looks complete AFAICT, although the contents is screwed up somehow.

Which build of TigerVNC are you using? Red Hat's? Have you tried our generic build? At first glance this looks like a bug in libjpeg-turbo rather than TigerVNC.

**Comment by bphinz** [comment] 2015-10-14 10:42
On Wed, Oct 14, 2015 at 2:56 AM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> Have you tried our client? Or TightVNC? Both support JPEG.
>
> What is TurboVNC erroring out on? The JPEG looks complete AFAICT, although
> the contents is screwed up somehow.
>
> Which build of TigerVNC are you using? Red Hat's? Have you tried our
> generic build? At first glance this looks like a bug in libjpeg-turbo
> rather than TigerVNC.
>
This was initially brought up on the TurboVNC users list and libjpeg-turbo
is what DRC first suspected as well.  He had Brett do some debugging to try
to rule out libjpeg-turbo and when the TurboVNC server was used (all other
things being equal), the corrupted image could not be reproduced so I asked
Brett to file a bug report on our issue tracker.  DRC suggested that it
might be an obscure bug in the JPEG encoder.  I don't have access to the
exact app that triggers it, but I do have some other tools from the same
vendor so I'll try those to see if I can reproduce the problem.

-brian

**Comment by CendioOssman** [comment] 2015-10-14 12:23
So I've read through the discussion there, and the build seems to be Red Hat's, but you've tried with an updated copy of libjpeg-turbo. So this would be a previously unknown bug.

**Comment by CendioOssman** [comment] 2015-10-14 12:25
I have an idea. Can you open up that exact schematic again and send us a screen shot from inside the VNC session? It would have to be exactly the same thing, not just something similar.

**Comment by brettwilliams** [comment] 2015-10-14 15:03
@CendioOssman TightVNC has no OSX client.  I will try with TigerVNC viewer and see if I can get the same result (I'll try to find the right JPEG settings).

As far as libjpeg-turbo, all of this started with TigerVNC server 1.3.0 on CentOS 6.4 and the 1.2.1 libjpeg-turbo shipped with it.  I've been upgrading pieces (starting with CentOS 6.5) to make sure this isn't fixed in later versions, including the newest libjpeg-turbo.  This has been done at the suggestions from folks at the TurboVNC list trying to narrow down the problem.

I don't think I can take a screenshot since the corrupt image is the first one sent it seems -- the client errors out immediately (I don't actually see the image of the circuit in question).

**Comment by CendioOssman** [comment] 2015-10-14 15:53
So do this: Get the client to a point where it crashes. Save the error jpeg file. Disable JPEG in the client and connect again. Take a screenshot. Attach both images here.

**Comment by brettwilliams** [comment] 2015-10-14 16:06
Here are the images.  Does it matter what format the screenshot is in?  Macs save PNG by default.

FYI -- here is the state of the session right now.  Works fine in TigerVNC using jpeg (though I didn't see how to exert much control over the encoding).

If I connect with TurboVNC, it immediately fails with corrupt jpeg.  If I disable jpeg in TurboVNC, it is ok (I used lossless zlib).  That's how I took the screenshot.  I could also take a screenshot from the session inside the TigerVNC viewer.

![screen shot 2015-10-14 at 9 58 46 am](https://cloud.githubusercontent.com/assets/752638/10489534/c05c779e-725a-11e5-8333-4ab35cdef7e9.png)
![error0](https://cloud.githubusercontent.com/assets/752638/10489616/fe313af0-725a-11e5-9d7e-6bdf22dbbed1.jpg)

**Comment by bphinz** [comment] 2015-10-14 16:53
On Wed, Oct 14, 2015 at 12:06 PM, brettwilliams <notifications@github.com>
wrote:

> Here are the images. Does it matter what format the screenshot is in? Macs
> save PNG by default.
>
> FYI -- here is the state of the session right now. Works fine in TigerVNC
> using jpeg (though I didn't see how to exert much control over the
> encoding).
>
> If I connect with TurboVNC, it immediately fails with corrupt jpeg. If I
> disable jpeg in TurboVNC, it is ok (I used lossless zlib). That's how I
> took the screenshot. I could also take a screenshot from the session inside
> the TigerVNC viewer.
>
OK, maybe I misunderstood...  So TigerVNC server/TigerVNC viewer works,
TigerVNC server/TurboVNC viewer fails, TurboVNC server/TurboVNC viewer
works, and TurboVNC server/TigerVNC client also works.  Is that correct?
The TigerVNC java viewer and TurboVNC java viewers share a common ancestry
- can you test the TigerVNC java client?  FWIW, I verified that I am able
to open up a design using Synopsys DC-Graphical using the TigerVNC 1.4
server and 1.5 java viewer with no issues.  Unfortunately, I can't access
the TurboVNC viewer here to test that though.

-brian

**Comment by brettwilliams** [comment] 2015-10-14 18:21
@bphinz Your summary is correct, except I did not try TurboVNC server/TigerVNC client.  I also just attempted the TigerVNC Java Viewer.  It does not fail.

It is only TurboVNC viewer with TigerVNC server using JPEG encoding that fails.  And it does so consistently.

**Comment by CendioOssman** [comment] 2015-10-15 08:18
![orig](https://cloud.githubusercontent.com/assets/6640916/10508219/e8aa5c18-7325-11e5-8e5d-d621a1fb0848.png)

Here is the original image data that corresponds to the bad JPEG rect. We should be able to test compression on this to see where things go wrong.

**Comment by CendioOssman** [comment] 2015-10-15 11:21
I'm not familiar with the TurboVNC viewer. Is there anyway you can figure out what quality and subsampling settings it is sending to the server?

**Comment by CendioOssman** [comment] 2015-10-15 11:59
Figured it out. `identify` claimed that the JPEG was produced at quality setting 95 and no subsampling. And I have a small test program that compresses that PNG, and does indeed produce the same kind of broken images.

**Comment by bphinz** [comment] 2015-10-15 12:38
On Thu, Oct 15, 2015 at 7:59 AM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> Figured it out. identify claimed that the JPEG was produced at quality
> setting 95 and no subsampling. And I have a small test program that
> compresses that PNG, and does indeed produce the same kind of broken images.
>
So it is an encoder issue then?

**Comment by CendioOssman** [comment] 2015-10-15 13:17
Problem found in libjpeg and PR issued (see ref. above). Closing this issue as it was never a bug in TigerVNC.

**Closed by CendioOssman** 2015-10-15 13:17 UTC
