### ISSUE TITLE
sending alt-tab to the server

### ISSUE THREAD

**Issue by grandinj** [TigerVNC/tigervnc#212] opened 2015-10-09 12:03 UTC
Hi

When working remotely on Ubuntu from a windows box, it would be nice to be able to have alt-tab commands go to the server, when I am working inside the window.
RealVNC seems to manage this.

Thanks, Noel

**Comment by CendioOssman** [comment] 2015-10-12 07:30
This is already possible in full screen mode. Are you saying you want it in windowed mode as well?

**Comment by grandinj** [comment] 2015-10-12 07:33
Hi Cendio, yes, that is what I would like.
I have large monitors, so I run VNC in a normal window, connected to an Ubuntu box where I do some of my development. When I'm in that window, I'd like to be able to switch between applications using ALT-TAB.

RealVNC calls this options "Pass special keys directly to VNC Server"

Thanks.

**Comment by CendioOssman** [comment] 2015-10-12 07:50
In that case it's a duplicate of issue #102.

**Closed by CendioOssman** 2015-10-12 07:50 UTC
