### ISSUE TITLE
Please implement the scaled mode

### ISSUE THREAD

**Issue by yurivict** [TigerVNC/tigervnc#1713] opened 2024-01-08 08:40 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes the host and guest screens have significantly different resolutions, and it's best to scale the guest screen to match the host screen. Particularly, when the fullscreen is used it's best if the screen is scaled to match the host's screen.

**Describe the solution you'd like**
Implement the 'scaled mode' option.

**Describe alternatives you've considered**
n/a

**Additional context**
Remmina does this very well: it allows the user to toggle the 'scaled mode' while the screen is active.

**Comment by samhed** [comment] 2024-01-08 08:55
Duplicate of #274

**Closed by samhed** 2024-01-08 08:55 UTC
Labels: duplicate
