### ISSUE TITLE
x0vncserver makes desktop crash and plant machine sometimes

### ISSUE THREAD

**Issue by AlexandreLemoine40** [TigerVNC/tigervnc#1589] opened 2023-01-30 09:21 UTC
If a client connects to my x0vncserver started on my computer and then he quits the connection, it will make the desktop environment black and sometimes it will show the login screen of my computer and sometimes black screen and I'll have to hard reset the computer. It occures 100% of the time when client quits the connection.

**To Reproduce**
1. Launch x0vncserver with the parameters you want (-rfbport, -localhost no etc...)
2. Launch Vinagr or any other VNC viewer
3. Connect to your x0vncserver using your IP and RFBPORT from your VNC Viewer 
4. Close the VNC connection from your client
5. The computer onwhich is launched x0vncserver will crash

**Expected behavior**
The computer onwhich is launched x0vncserver shouldn't crash when a viewer closes a connection.

**Client (please complete the following information):**
 - OS: Debian 11
 - VNC client: Vinagr (any other VNC Viewer does the same behaviour about the crash)

**Server (please complete the following information):**
 - OS: Debian 11
 - VNC server: TigerVNC (x0vncserver)
 - VNC server version: 1.13
 - Server downloaded from: https://github.com/TigerVNC/tigervnc/releases
 - Server was started using: x0vncserver

**Comment by CendioOssman** [comment] 2023-01-31 11:49
Unfortunately, it sounds like a bug in your X server, which we are unable to help out with. We could have a look at the logs, though, and see if there are any clues that can help us point you in the right direction.

Can you dig out some log from the local session when this problem happens? It should be in the user or system journal.

**Comment by CendioOssman** [comment] 2023-02-28 15:15
This is likely a duplicate of #1595.

**Closed by CendioOssman** 2023-02-28 15:15 UTC
