### ISSUE TITLE
FreeRDP remote desktop launch inside tigerVNC, it brought down the tigerVNC

### ISSUE THREAD

**Issue by akklaw** [TigerVNC/tigervnc#992] opened 2020-04-09 16:46 UTC
**Describe the bug**
Have tigerVNC up and running, inside TigerVNC's shell, launch FreeRDP remote desktop to connect to windows server 2016.  TigerVNC quits with the following error.  I have discussed this issue with FreeRDP, they suggests to create a bug for TigerVNC.  This appears to be TigerVNC issue.

XIO: fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
after 71 requests (71 known processed) with 2 events remaining

**To Reproduce**
1. Launch vnc viewer as vncviewer <hostname>:5900
2. within the vnc viewer launch xfreerdp 
3. vnc viewer quits with the IO error.

**Expected behavior**
FreeRDP remoteDesktop launch successfully within TigerVNC viewer.

**Client (please complete the following information):**
 - OS: RHEL 7.6
 - VNC client: TigerVNC
 - VNC client version: TigerVNC Viewer 64-bit v1.8.0

**Server (please complete the following information):**
 - OS: RHEL 7.6

Additional context: Log from freeRDP.

[20:04:46:016] [20226:20226] [DEBUG][com.freerdp.client.common] - This is Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type: Release
CFLAGS: -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler: GNU, 4.4.7
Target architecture: x64

[20:04:46:016] [20226:20227] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[20:04:46:017] [20226:20227] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[20:04:46:017] [20226:20227] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[20:04:46:017] [20226:20227] [DEBUG][com.freerdp.channels.cliprdr.client] - VirtualChannelEntryEx
[20:04:46:017] [20226:20227] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[20:04:46:017] [20226:20227] [DEBUG][com.freerdp.channels.drdynvc.client] - VirtualChannelEntryEx
[20:04:46:017] [20226:20227] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[20:04:46:018] [20226:20227] [DEBUG][com.freerdp.client.x11] - Searching for XInput pointer device
[20:04:46:018] [20226:20227] [DEBUG][com.freerdp.client.x11] - Pointer device: 6
[20:04:46:066] [20226:20227] [DEBUG][com.freerdp.primitives] - primitives benchmark result:
[20:04:47:228] [20226:20227] [DEBUG][com.freerdp.primitives] - * generic= 23
[20:04:47:379] [20226:20227] [DEBUG][com.freerdp.primitives] - * optimized= 114
[20:04:47:379] [20226:20227] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized
[20:04:47:382] [20226:20227] [DEBUG][com.freerdp.core.nego] - Enabling security layer negotiation: TRUE
[20:04:47:382] [20226:20227] [DEBUG][com.freerdp.core.nego] - Enabling restricted admin mode: FALSE
[20:04:47:382] [20226:20227] [DEBUG][com.freerdp.core.nego] - Enabling RDP security: TRUE
[20:04:47:382] [20226:20227] [DEBUG][com.freerdp.core.nego] - Enabling TLS security: TRUE
[20:04:47:382] [20226:20227] [DEBUG][com.freerdp.core.nego] - Enabling NLA security: TRUE
[20:04:47:382] [20226:20227] [DEBUG][com.freerdp.core.nego] - Enabling NLA extended security: FALSE
[20:04:47:382] [20226:20227] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_NLA
[20:04:47:382] [20226:20227] [DEBUG][com.freerdp.core.nego] - Attempting NLA security
[20:04:47:382] [20226:20227] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[20:04:47:382] [20226:20227] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[20:04:47:383] [20226:20227] [DEBUG][com.freerdp.core] - connecting to peer 172.17.4.107
[20:04:47:384] [20226:20227] [DEBUG][com.freerdp.core.nego] - RequestedProtocols: 3
[20:04:47:397] [20226:20227] [DEBUG][com.freerdp.core.nego] - RDP_NEG_RSP
[20:04:47:397] [20226:20227] [DEBUG][com.freerdp.core.nego] - selected_protocol: 2
[20:04:47:397] [20226:20227] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_FINAL
[20:04:47:398] [20226:20227] [DEBUG][com.freerdp.core.nego] - Negotiated NLA security
[20:04:47:398] [20226:20227] [DEBUG][com.freerdp.core.nego] - nego_security_connect with PROTOCOL_HYBRID
[20:04:47:408] [20226:20227] [DEBUG][com.winpr.sspi] - InitSecurityInterfaceExA
[20:04:47:408] [20226:20227] [DEBUG][com.freerdp.core.nla] - nla_client_init 412 : packageName=Negotiate ; cbMaxToken=12256
[20:04:47:408] [20226:20227] [TRACE][com.freerdp.core.nla] - InitializeSecurityContext status SEC_I_CONTINUE_NEEDED [0x00090312]
[20:04:47:408] [20226:20227] [DEBUG][com.freerdp.core.nla] - Sending Authentication Token
[20:04:47:508] [20226:20227] [DEBUG][com.freerdp.core.nla] - CredSSP protocol support 6, peer supports 6
[20:04:47:508] [20226:20227] [TRACE][com.freerdp.core.nla] - InitializeSecurityContext SEC_I_COMPLETE_NEEDED [0x00090313]
[20:04:47:508] [20226:20227] [DEBUG][com.freerdp.core.nla] - Sending Authentication Token
[20:04:47:709] [20226:20227] [DEBUG][com.freerdp.core.gcc] - Server rdp encryption method: NONE
[20:04:48:511] [20226:20227] [DEBUG][com.freerdp.core.info] - Client Info Packet Flags = INFO_MOUSE|INFO_DISABLECTRLALTDEL|INFO_UNICODE|INFO_MAXIMIZESHELL|INFO_LOGONNOTIFY|INFO_COMPRESSION|INFO_ENABLEWINDOWSKEY|INFO_FORCE_ENCRYPTED_CS_PDU|INFO_LOGONERRORS|INFO_MOUSE_HAS_WHEEL|INFO_NOAUDIOPLAYBACK
[20:04:48:511] [20226:20227] [DEBUG][com.winpr.timezone] - tz: Bias=0 sn='Coordinated Universal Time' dln='Coordinated Universal Time'
[20:04:48:013] [20226:20227] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x1f size=37 channelId=1009)
[20:04:48:013] [20226:20227] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x14 size=41 channelId=1009)
[20:04:48:013] [20226:20227] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x14 size=41 channelId=1009)
[20:04:48:013] [20226:20227] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x2b size=57 channelId=1009)
[20:04:48:013] [20226:20227] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x27 size=41 channelId=1009)
[20:04:48:013] [20226:20227] [DEBUG][com.freerdp.core.rdp] - recv Monitor Layout Data PDU (0x37), length: 42
[20:04:48:113] [20226:20227] [DEBUG][com.freerdp.core.rdp] - recv Synchronize Data PDU (0x1F), length: 22
[20:04:48:113] [20226:20227] [DEBUG][com.freerdp.core.rdp] - recv Control Data PDU (0x14), length: 26
[20:04:48:113] [20226:20227] [DEBUG][com.freerdp.core.rdp] - recv Control Data PDU (0x14), length: 26
[20:04:48:113] [20226:20227] [DEBUG][com.freerdp.core.rdp] - recv
XIO: fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
after 71 requests (71 known processed) with 2 events remaining

**Comment by MarkMielke** [comment] 2020-04-11 05:39
Try turning off backing store by passing "-bs" to Xvnc. It's been a while since I looked into this problem, so my memory will need a refresh, but if you could confirm if "-bs" clears the symptoms, this will ensure I'm remembering the right one and I can try to find all of the evidence.

As I recall, Red Hat chose to change from the upstream Xorg behaviour where backing store is enabled only by application request, to backing store always enabled around RHEL 7.6 as a Red Hat specific patch in Xorg. As TigerVNC is built on top of Xorg, it inherits the behaviour of the Xorg it is compiled against. Since you are probably using TigerVNC built by Red Hat, against the Red Hat Xorg patch to always enable backing store, you are getting Red Hat behaviour. This then may have nothing to do with TigerVNC, and you should take this up with Red Hat.

I noted a few failures related to this. One was xfreerdp. However, I have found it to be pretty rare (and most of my users don't use xfreerdp), so I still use "-bs" for myself on RHEL-based systems and I haven't yet determined what course of action to take on this. For example - one course of action would be to rebuild Xorg without Red Hat's patch, and use the xorg-x11-server-source without Red Hat's patch, to build TigerVNC.

**Comment by MarkMielke** [comment] 2020-04-11 05:43
This was the patch I'm talking about:

* Thu Aug 09 2018 Adam Jackson <ajax@redhat.com> - 1.20.1-1
- xserver 1.20.1
- Enable backing store's Always mode

**Comment by MarkMielke** [comment] 2020-04-11 05:56
Ok... I found my previous research. Here is a portion of it that I am willing to share. Please note that the conclusion applies to both TigerVNC *and* direct use of Xorg on a physical workstation. So, this is not really a TigerVNC problem at all...

“Backing Store” is a very old optional feature in X11 that you can read about here:

> https://en.wikipedia.org/wiki/X_Window_System_core_protocol#Windows
>
> The content of a window is not always guaranteed to be preserved over time. In particular, the window content may be destroyed when the window is moved, resized, covered by other windows, and in general made totally or partly non-visible. In particular, content is lost if the X server is not maintaining a backing store of the window content. The client can request backing store for a window to be maintained, but there is no obligation for the server to do so. Therefore, clients cannot assume that backing store is maintained. If a visible part of a window has an unspecified content, an event is sent to notify the client that the window content has to be drawn again.
>
> Every window has an associated set of attributes, such as the geometry of the window (size and position), the background image, whether backing store has been requested for it, etc. The protocol includes requests for a client to inspect and change the attributes of a window.

If “Backing Store” is disabled for a window, then every time any portion of the window is “exposed” (made visible to the user), then the application is asked to redraw that portion of the screen. This is done via an “Expose” window event that is sent to the application, and the application responds with a series of draw / paint requests.

If “Backing Store” is enabled for a window, then every time any portion of the window is “exposed” (made visible to the user), then the X.org server can fill the portion from the backing store without needing to ask the application to do it, so no “Expose” window events are sent.

This optional feature has traditionally been “opt-in”. Basically, applications that know about it, and know how to take advantage of it, request for individual windows under their control to have “Backing Store” enabled. This means that applications that don’t know about it, normally don’t have it enabled.

Red Hat introduced this change into the X.org server in RHEL 7.6, which Oracle Linux inherited in OL 7.6, and which TigerVNC built for OL 7.6, inherited from OL 7.6:

```
* Thu Aug 09 2018 Adam Jackson <ajax@redhat.com> - 1.20.1-1
- xserver 1.20.1
- Enable backing store's Always mode
```

This enables backing store for *all* windows, whether the application asked for it or not. This also means that it enabled backing store for all application whether *tested* or not.

This caused all of these sorts of problems:

- Applications that expect the “Expose” events to arrive, are no longer receiving them. This may be the cause when applications fail to start properly, but the server doesn’t crash.
- It may have exposed bugs in the underlying backing store implementation that were never encountered before, for example: https://gitlab.freedesktop.org/xorg/xserver/issues/623 . This may be the cause of the entire server crashing with xfreerdp.
- Screen tearing. With backing store enabled on a physical workstation with a graphics card, it disables several of the “direct draw” 2d and 3d accelerations available. Instead of translating draw requests to draw requests, the draw requests are being sent to a backing store pixel map, and then the pixel map is later copied to the screen. This double buffering is the one I was looking into closer due to various reports of users about screen tearing. I’ve asked a few of them to try out disabling Backing Store to see if it helps.
 
The reason why backing store is desired, is because:

- Some applications don’t work properly with it off. Forcing it on can help.
- Performance can be significantly improved. For applications that render very complex set of objects, it can be very expensive to redraw each of the objects every time the user switches which window is on the “top” of their screen. With backing store, the application draws the complex objects to an off-screen pixel map, and the X compositor just copies it from the backing store in the final rendered form whenever it is required. Also, for applications that are running remotely, with a DISPLAY set to a different server, this can significantly improve performance because it removes network latency for the drawing requests.

The “-bs” flag is a bit of a hammer:

> https://www.x.org/archive/X11R6.8.1/doc/Xserver.1.html
> 
>     -bs
> 
>         disables backing store support on all screens.

In RHEL 7.5 and before, and RHEL 6.6 and before, backing store was enabled only for applications that asked for it, and one would presume only for applications that had been tested with it enabled.

In RHEL 7.6 and later, and RHEL 6.7 and later, backing store is forcefully enabled for all screens, whether applications want it or not.

With RHEL 7.6 and later, and “-bs”, backing store is disabled for all applications whether they ask for it or not.

**Comment by MarkMielke** [comment] 2020-04-11 06:03
Reviewing this - I'm also reminded of my recent review of RHEL 7.8 release notes, including changes to Xorg. This one comes to mind as being potentially relevant:

```
* Tue Aug 13 2019 Adam Jackson <ajax@redhat.com> - 1.20.4-9
- Fix a crash when destroying a redirected window with backing store
```

I also see now that they updated TigerVNC as well in RHEL 7.8, and included this changelog:

```
* Tue Aug 13 2019 Adam Jackson <ajax@redhat.com> - 1.8.0-18
- Rebuild against newer X server to pick up backing store crash fixes
  Resolves: bz#1670342
```

Unfortunately, I'm not authorized to see that Bugzilla so I can't see what it says. But, it's possible that this is one of several Xorg bugs that might be affecting you, that might be fixed in RHEL 7.8, and might be fixed in TigerVNC built against RHEL 7.8.

**Comment by MarkMielke** [comment] 2020-04-11 06:38
2 of the 3ixes in RHEL 7.8 Xorg:

- https://gitlab.freedesktop.org/xorg/xserver/-/commit/0f477cc68bbfe37555f73313dcc50b303c3ca210
- https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/261

Some more discussion:
- https://bugzilla.redhat.com/show_bug.cgi?id=1671183
- https://bugzilla.redhat.com/show_bug.cgi?id=1769610

**Comment by CendioOssman** [comment] 2020-04-13 10:52
@akklaw, could you check if `-bs` helps? If so then this is likely a duplicate of #979.

**Comment by akklaw** [comment] 2020-04-13 19:17
Using -bs (no backing-store) in Xorg solved the problem.  Thank you for your help.

**Comment by CendioOssman** [comment] 2020-04-16 10:51
Thanks for testing. Could you describe how you are starting the VNC server and which desktop environment you are using? I'd like to see if I can reproduce the issue for debugging #979.

**Closed by CendioOssman** 2020-04-16 10:51 UTC

**Comment by akklaw** [comment] 2020-04-16 18:48
I did not do anything with VNC server, I put -bs (no backing-store) option to start Xorg.

**Comment by CendioOssman** [comment] 2020-04-17 06:23
I'm afraid I don't follow. And I was unable to reproduce the issue on my RHEL 7 server here. So I would be very thankful if you could give me more details on your setup so I can duplicate it here.

**Comment by akklaw** [comment] 2020-04-17 14:19
The host is running RHEL 7.6, x11vnc is the vnc server, tigerVNC is the VNC client.  Inside TigerVNC, running FreeRDP remtoe desktop connects to windows server 2016 which is running inside kvm that runs in RHEL 7.6 in the same Linue Host.  That is the setup, hope this helps.  I added -bs to Xorg server in RHEL 7.6 and I didn't touch the options in x11vnc server and tigerVNC.

**Comment by CendioOssman** [comment] 2020-04-20 06:50
Ah, I see. Then this was unfortunately never a TigerVNC issue and is not directly related to #979 (even though it's probably the same underlying Xorg bug). Thank you for explaining.
