### ISSUE TITLE
TigerVNC fills Xorg.0.log with "DDC gathered Modelines"

### ISSUE THREAD

**Issue by rnmixon** [TigerVNC/tigervnc#1726] opened 2024-02-08 23:12 UTC
**Problem Description**

When TigerVNC service tigervncserver@:1.service run it causes the following sequence of lines to be dumped into Xorg.0.log repeatedly (greater than once per second), filling up disk space:
```
n2kowner@RichZ3:/etc/X11$ tail -25 /var/log/Xorg.0.log
[  7036.845] (II) modeset(0): Modeline "1920x1200"x0.0  154.00  1920 1968 2000 2080  1200 1203 1209 1235 +hsync -vsync (74.0 kHz e)
[  7037.009] (II) modeset(0): EDID vendor "DVA", prod id 60001
[  7037.009] (II) modeset(0): DDCModeFromDetailedTiming: 1280x800 Warning: We only handle separate sync.
[  7037.010] (II) modeset(0): Using hsync ranges from config file
[  7037.010] (II) modeset(0): Using vrefresh ranges from config file
[  7037.010] (II) modeset(0): Printing DDC gathered Modelines:
[  7037.010] (II) modeset(0): Modeline "1024x768"x0.0   65.00  1024 1048 1184 1344  768 771 777 806 -hsync -vsync (48.4 kHz eP)
[  7037.010] (II) modeset(0): Modeline "1280x768"x0.0   79.50  1280 1344 1472 1664  768 771 778 798 -hsync +vsync (47.8 kHz e)
[  7037.010] (II) modeset(0): Modeline "1360x768"x0.0   85.50  1360 1424 1536 1792  768 771 777 795 +hsync +vsync (47.7 kHz e)
[  7037.010] (II) modeset(0): Modeline "1366x768"x0.0   85.50  1366 1436 1579 1792  768 771 774 798 +hsync +vsync (47.7 kHz e)
[  7037.010] (II) modeset(0): Modeline "1280x800"x0.0   83.50  1280 1352 1480 1680  800 803 809 831 -hsync +vsync (49.7 kHz e)
[  7037.010] (II) modeset(0): Modeline "1440x900"x0.0  106.50  1440 1520 1672 1904  900 903 909 934 -hsync +vsync (55.9 kHz e)
[  7037.010] (II) modeset(0): Modeline "1680x1050"x0.0  146.25  1680 1784 1960 2240  1050 1053 1059 1089 -hsync +vsync (65.3 kHz e)
[  7037.010] (II) modeset(0): Modeline "800x600"x0.0   40.00  800 840 968 1056  600 601 605 628 +hsync +vsync (37.9 kHz e)
[  7037.010] (II) modeset(0): Modeline "640x480"x0.0   25.18  640 656 752 800  480 490 492 525 -hsync -vsync (31.5 kHz e)
[  7037.010] (II) modeset(0): Modeline "720x400"x0.0   28.32  720 738 846 900  400 412 414 449 -hsync +vsync (31.5 kHz e)
[  7037.010] (II) modeset(0): Modeline "1280x960"x0.0  108.00  1280 1376 1488 1800  960 961 964 1000 +hsync +vsync (60.0 kHz e)
[  7037.010] (II) modeset(0): Modeline "1280x1024"x0.0  108.00  1280 1328 1440 1688  1024 1025 1028 1066 +hsync +vsync (64.0 kHz e)
[  7037.010] (II) modeset(0): Modeline "1280x720"x60.0   74.48  1280 1336 1472 1664  720 721 724 746 -hsync +vsync (44.8 kHz e)
[  7037.010] (II) modeset(0): Modeline "1400x1050"x0.0  101.00  1400 1448 1480 1560  1050 1053 1057 1080 +hsync -vsync (64.7 kHz e)
[  7037.010] (II) modeset(0): Modeline "1600x1200"x0.0  162.00  1600 1664 1856 2160  1200 1201 1204 1250 +hsync +vsync (75.0 kHz e)
[  7037.010] (II) modeset(0): Modeline "1920x1200"x0.0  154.00  1920 1968 2000 2080  1200 1203 1209 1235 +hsync -vsync (74.0 kHz e)``` 

**To Reproduce**
Steps to reproduce the behavior:
1. sudo apt install tigervnc-standalone-server tigervnc-xorg-extension tigervnc-common dbus-x11
2. sudo systemctl start tigervncserver@:1.service
3. tail -f  /var/log/Xorg.0.log

**Expected behavior**
Smaller Xorg.0.log file similar to what we had for "Xvnc TigerVNC 1.7.0".

**Screenshots**
N/A

**Client (please complete the following information):**
 - OS: Ubuntu 22.04.3
 - VNC client: noVNC
 - VNC client version: 1.4.0
 - Client downloaded from: [[[e.g. my Linux distribution](https://github.com/novnc/noVNC/releases/tag/v1.4.0)]](https://github.com/novnc/noVNC/releases/tag/v1.4.0)

**Server (please complete the following information):**
 - OS: Ubuntu 22.04.3
 - VNC server: TigerVNC
 - VNC server version: 1.12.0
 - Server downloaded from: Ubuntu Server 22.04.3
 - Server was started using: sudo systemctl start tigervncserver@:1.service

**Additional context**
Hardware is an embedded black box with Atom E3845 SOC. Hardware info follows:

```
n2kowner@RichZ3:~/.vnc$ sudo lshw -short
H/W path           Device     Class          Description
========================================================
                              system         VT_mIPC_BT35M X64 (Type1 - SKU0)
/0                            bus            Type2 - Board Product Name
/0/0                          memory         64KiB BIOS
/0/4                          processor      Intel(R) Atom(TM) CPU  E3845  @ 1.91GHz
/0/4/8                        memory         32KiB L1 cache
/0/4/9                        memory         1MiB L2 cache
/0/7                          memory         24KiB L1 cache
/0/25                         memory         2GiB System Memory
/0/25/0                       memory         2GiB SODIMM DDR3 Synchronous 1333 MHz (0.8 ns)
/0/25/1                       memory         SODIMM DDR3 Synchronous 1333 MHz (0.8 ns) [empty]
/0/100                        bridge         Atom Processor Z36xxx/Z37xxx Series SoC Transaction Register
/0/100/2           /dev/fb0   display        Atom Processor Z36xxx/Z37xxx Series Graphics & Display
/0/100/13          scsi1      storage        Atom Processor E3800 Series SATA AHCI Controller
/0/100/13/0.0.0    /dev/sda   disk           8012MB mSATA mini 3SE4
/0/100/13/0.0.0/1  /dev/sda1  volume         127MiB Windows FAT volume
/0/100/13/0.0.0/2  /dev/sda2  volume         7512MiB EXT4 volume
/0/100/14                     bus            Atom Processor Z36xxx/Z37xxx, Celeron N2000 Series USB xHCI
/0/100/14/0        usb1       bus            xHCI Host Controller
/0/100/14/0/2                 bus            USB 2.0 Hub
/0/100/14/0/2/2               communication  USBCAN (CAN-USB Gateway)
/0/100/14/0/2/4               bus            USB hub
/0/100/14/0/2/4/1             communication  VCOM Port
/0/100/14/0/2/4/2  input21    input          eGalax Inc. eGalaxTouch EXC7200-747Cv1.002           Stylus
/0/100/14/0/3                 input          USB Receiver
/0/100/14/0/3/0    input17    input          Logitech M510
/0/100/14/0/4      input12    input          Dell Dell USB Keyboard
/0/100/14/1        usb2       bus            xHCI Host Controller
/0/100/18                     generic        Atom Processor Z36xxx/Z37xxx Series LPIO2 DMA Controller
/0/100/18.1                   bus            Atom Processor Z36xxx/Z37xxx Series LPIO2 I2C Controller #1
/0/100/1a                     generic        Atom Processor Z36xxx/Z37xxx Series Trusted Execution Engine
/0/100/1b          card0      multimedia     Atom Processor Z36xxx/Z37xxx Series High Definition Audio Controller
/0/100/1b/0        input25    input          HDA Intel PCH HDMI/DP,pcm=3
/0/100/1b/1        input26    input          HDA Intel PCH HDMI/DP,pcm=7
/0/100/1c                     bridge         Atom Processor E3800 Series PCI Express Root Port 1
/0/100/1c/0        eth0       network        82574L Gigabit Network Connection
/0/100/1c.1                   bridge         Atom Processor E3800 Series PCI Express Root Port 2
/0/100/1c.2                   bridge         Atom Processor E3800 Series PCI Express Root Port 3
/0/100/1e                     generic        Atom Processor Z36xxx/Z37xxx Series LPIO1 DMA Controller
/0/100/1e.5                   bus            Atom Processor Z36xxx/Z37xxx Series LPIO1 SPI Controller
/0/100/1f                     bridge         Atom Processor Z36xxx/Z37xxx Series Power Control Unit
/0/100/1f/0                   system         PnP device PNP0b00
/0/100/1f/1                   system         PnP device PNP0c02
/0/100/1f/2                   input          PnP device PNP0303
/0/100/1f/3                   input          PnP device PNP0f03
/0/100/1f/4                   communication  PnP device PNP0501
/0/100/1f/5                   communication  PnP device PNP0501
/0/100/1f/6                   system         PnP device PNP0c02
/0/100/1f/7                   system         PnP device PNP0c31
/0/100/1f.3                   bus            Atom Processor E3800/CE2700 Series SMBus Controller
/1                            power          SR Real Battery
/2                            power          OEM_Define5
/3                 input0     input          Power Button
/4                 input1     input          Sleep Button
/5                 input2     input          Power Button
/6                 input6     input          Video Bus
n2kowner@RichZ3:~/.vnc$
```

**Comment by CendioOssman** [comment] 2024-02-09 11:32
I see you've also written to the tigervnc-users lists, so let's close this issue so we don't have a discussion in two places.

**Closed by CendioOssman** 2024-02-09 11:32 UTC

**Comment by rnmixon** [comment] 2024-02-09 15:33
> I see you've also written to the tigervnc-users lists, so let's close this issue so we don't have a discussion in two places.

I actually posted twice to the tigervnc-users list but never did see the post show up - that's why I opened the issue. I've used Google Groups before, but must be missing something.

**Comment by CendioOssman** [comment] 2024-02-12 12:49
I'm afraid new users need to wait for approval of their posts, as we've had numerous issues with spambots as of late.

**Comment by ms4sman** [comment] 2024-11-19 13:55
Could you provide a link to the discussion about this elsewhere? I was not able to find it, and I am having this same issue and would like to know if a solution was found.

**Comment by CendioOssman** [comment] 2024-11-19 13:59
It seems it has been deleted. I am not sure if it was by the poster, or by Google.

**Comment by ms4sman** [comment] 2024-11-19 14:01
I see. Thank you for the quick reply. Would it be OK if I open a new issue here about it then? I am having a very similar issue to what the OP described here.

**Comment by CendioOssman** [comment] 2024-11-19 14:25
The issue is not obviously a TigerVNC issue, given that it's the Xorg side of things that is misbehaving. So I would suggest the discussion group first to figure out what is triggering the problem.
