### ISSUE TITLE
tiger vnc viewer (1.10.1) closes after I provide valid password

### ISSUE THREAD

**Issue by DaXmAn** [TigerVNC/tigervnc#968] opened 2020-02-14 18:30 UTC
**Describe the bug**
I have TigerVNC v1.10.1 server working from Windows10. Configured to use TLS with X.509 self signed certificate.

When I try to connect from another machine in the same LAN vncwiever (1.10.1) ask me for password, once I provide valid password, nothing happens, client closes. Process ends.

In the log I see this:

Fri Feb 14 19:20:21 2020
 DecodeManager: Detected 8 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 TcpSocket:   Connecting to 192.168.0.168 [192.168.0.168] port 5900
 CConn:       Connected to host 192.168.0.168 port 5900
 CConnection: reading protocol version
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: processing security types message
 CConnection: Server offers security type VeNCrypt(19)
 CConnection: Server offers security type VeNCrypt(19)
 CConnection: Choosing security type VeNCrypt(19)
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CVeNCrypt:   Server offers security type X509Vnc (261)
 CVeNCrypt:   Choosing security type X509Vnc (261)
 CConnection: processing security message
 TLS:         Could not load system certificate trust store
 TLS:         X509 session has been set
 CConnection: processing security message
 CConnection: processing security message
 TLS:         TLS handshake completed with
              (TLS1.2)-(ECDHE-RSA-SECP256R1)-(AES-256-GCM)
 TLS:         hostname mismatch

Fri Feb 14 19:20:31 2020
 CConnection: processing security result message
 CConnection: processing security result message
 CConn:       End of stream

**To Reproduce**
1. Open TigerVNC viewer
2. Provide IP address
3. Connect to vnc server
4. Click "Yes" to continue when warned about the certificate being signed by an unknown authority.
5. Provide valid password

**Expected behavior**
Connect to VNC server

**Screenshots**
N/A

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNC 
 - VNC client version: 1.10.1
 - Client downloaded from: TigerVNC official source/page

**Server (please complete the following information):**
 - OS: Windows 10
 - VNC server: TigerVNC
 - VNC server version: 1.10.1
 - Server downloaded from: TigerVNC official source/page
 - Server was started using: windows service, winvnc4.exe -noconsole -start

**Additional context**
Configuration made via TigerVNC GUI

**Comment by mgorges** [comment] 2020-02-16 03:20
This sounds a bit like #943. I can also confirm that closing of the window is independent of the tigervnc client version and operating system - having tried both 1.8, 1.9, and 1.10 on macos and 1.8 on windows.

**Comment by mgorges** [comment] 2020-02-16 03:32
Also duplicate of #946, #930 - the nightly builds are at http://tigervnc.bphinz.com/nightly/, will try that tomorrow.

**Comment by samhed** [comment] 2020-02-17 09:16
Thanks @mgorges, @DaXmAn could you also try a nightly build please?

**Comment by DaXmAn** [comment] 2020-02-17 14:06
Nightly build of server from here http://tigervnc.bphinz.com/nightly/windows/tigervnc64-1.10.80.exe
works with same tiger vnc client.

**Comment by CendioOssman** [comment] 2020-02-17 15:21
I think we need to see what the server says here. Could you enable some debug logs and post the result here? Instructions are available in our wiki.

**Comment by mgorges** [comment] 2020-02-24 19:19
I can confirm that using the nightly build of the server fixes this issues for me. - Might I suggest you do a new release to prevent others from running into the same problem?

**Comment by CendioOssman** [comment] 2020-02-27 12:42
Thank you for testing. A new release will be posted in time, but until then feel free to continue using the nightly builds.

**Closed by CendioOssman** 2020-02-27 12:42 UTC
Labels: duplicate

**Comment by deedubb** [comment] 2020-04-08 18:26
Can anyone post http://tigervnc.bphinz.com/nightly/windows/tigervnc64-1.10.80.exe? The URL is now broken

**Comment by dbolton** [comment] 2020-04-09 19:19
@deedubb It looks like your link is working again today.
