### ISSUE TITLE
Garbled screen on update to tigervnc-1.14.0-1

### ISSUE THREAD

**Issue by escuta** [TigerVNC/tigervnc#1793] opened 2024-07-29 16:23 UTC
**Describe the bug**
Screen is garbled when accessing the remote Arch Linux device after update to tigervnc-1.14.0-1. This is true when using vncviewer on Arch Linux and when using bVNC Free on Android. 

**To Reproduce**
1. Make ssh tunnel to remote device: eg. ssh 192.168.15.111 -L 9901:localhost:5901
2. Open viewer: eg. vncviewer localhost:9901
3. Screen is garbled. Looks like an anti-stain carpet in a cheap hotel.

**Expected behavior**
There should be a nice readable screen 

**Screenshots**

![image](https://github.com/user-attachments/assets/6e8c1624-5e94-4b61-b16a-9f4451994c6e)

**Client (please complete the following information):**
 - OS: Arch Linux
 - VNC client: TigerVNC Viewer v1.14.0
 - VNC client version: v1.14.0
 - Client downloaded from: Arch

**Server (please complete the following information):**
 - OS: Arch Linux (Aarch64 - Raspberry Pi 4)
 - VNC server:TigerVNC
 - VNC server version: 1.14.0-1
 - Server downloaded from: Arch
 - Server was started using: systemctl
 - 
**Additional context**

Works again if i downgrade to the pacman package tigervnc-1.13.1-5-aarch64.pkg.tar.xz

**Comment by CendioOssman** [comment] 2024-07-30 08:15
This seems to be a duplicate of #1790. Let's merge the two and see if we can figure out what is going on.

**Closed by CendioOssman** 2024-07-30 08:15 UTC
