### ISSUE TITLE
Clipboard (copy from client host to active vnc session) no longer working consistently

### ISSUE THREAD

**Issue by durack1** [TigerVNC/tigervnc#269] opened 2016-02-12 18:53 UTC
I recently upgraded my `tigervnc` installation to `1.6.0`. Since upgrading the function of the clipboard, copying text from the client host to the active vnc session no longer works consistently.

It seems that upon opening a new vnc window the clipboard/copy function works for a short period of time (one copy), before becoming unresponsive. Closing the vnc window and opening a new window seems to lead to the same behavior.

Would diagnostic info be useful here - and if so what?

tigervnc version: 

```
[duro@ocean]$ Xvnc -version
Xvnc TigerVNC 1.6.0 - built Dec 24 2015 16:05:46
Copyright (C) 1999-2015 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11202000, The X.Org Foundation
```

The client host is both `Windows 10` and `OS X 10.10.5` running the `realvnc viewer v5.3.0`
##

**Comment by CendioOssman** [comment] 2016-02-15 14:23
Do you get these issues if you use some other client (e.g. ours)?

Does it continue to work fine from server to the client?

**Comment by durack1** [comment] 2016-02-16 18:47
Thanks @CendioOssman, is there an `OS X` viewer available? I can only see `Windows` viewers on the download page https://bintray.com/tigervnc/stable/tigervnc/1.6.0

**Comment by bphinz** [comment] 2016-02-16 18:58
On Tue, Feb 16, 2016 at 1:47 PM, Paul J. Durack <notifications@github.com>
wrote:

> Thanks @CendioOssman <https://github.com/CendioOssman>, is there an OS X
> viewer available? I can only see Windows viewers on the download page
> https://bintray.com/tigervnc/stable/tigervnc/1.6.0
>
Yes, there is an OS X viewer.  Look on that page for the file:
TigerVNC-1.6.0.dmg.

-brian

**Comment by durack1** [comment] 2016-02-16 19:13
@bphinz great thanks for the tipoff, am testing now and at least currently seems to be working as expected.

**Comment by durack1** [comment] 2016-02-17 00:11
@CendioOssman @bphinz it would appear this issue is a problem with the `realVNC` client, so please feel free to close.

I've been happily using the `tigerVNC` client most of today and have had client -> host and host -> client clipboard happily working, persistently.

**Comment by CendioOssman** [comment] 2016-02-17 10:25
Great. Closing.

**Comment by durack1** [comment] 2016-02-17 23:49
@CendioOssman @bphinz, bad news.. The same problem has now started happening with my `TigerVNC 1.6.0` client..

**Comment by CendioOssman** [comment] 2016-02-18 12:52
Have you found a way to quickly reproduce it?

**Comment by bphinz** [comment] 2016-02-18 13:20
Paul,

How are you starting vncconfig? Can you try using 'vncconfig -nowin -poll
1000' and see if that fixes things? I've found -poll to be basically a
necessity in order to make clipboard transfers work reliably, but I don't
remember in which direction the problem always seemed to be...


-brian

**Comment by durack1** [comment] 2016-02-18 16:49
@bphinz thanks for the tip.. I've just restarted `vncconfig` using your argument suggestions above and will see how things go today..

FYI, I have just been using:
```
> vncconfig &
```
Up until now..

**Comment by CendioOssman** [comment] 2016-02-25 08:41
I'm planning on dropping the clipboard components from vncconfig and moving them in to Xvnc. So poll will disappear. OTOH any bugs that would need it as a workaround should not affect the new code.

**Comment by durack1** [comment] 2016-02-25 20:59
@CendioOssman I think that's a great step forward.. I was always curious why I had to actively start `vncconfig` myself, rather than it being initialised automagically when a new `vnc` session is instantiated - automating/merging this is a step in the right direction to me

**Comment by CendioOssman** [comment] 2016-02-26 08:39
Unfortunately I don't think it is likely to solve your issue though. So how has the testing gone?

**Comment by qzo** [comment] 2016-02-26 11:03
I'm using tightvncserver (on Debian (Raspbian) Jessie stable) and connecting using TigerVNC Viewer (1.6.0, 64bit) on Windows 8.1. Copying from the remote computer (running tightvncserver) works fine, copying from the local (TightVNC Viewer) computer randomly stops working. After closing the Viewer and opening it again, everything starts working correctly (at least for some time).

**Comment by CendioOssman** [comment] 2016-02-26 11:15
Let's focus on the case of TigerVNC to TigerVNC for now as otherwise we might be complicating things with bugs in other projects.

**Comment by durack1** [comment] 2016-03-03 22:32
@CendioOssman is my testing it appears that the instances of clipboard failure have reduced, but there are still some quirky cases where I need to copy items twice before they correctly map back and forth into the client

**Comment by bphinz** [comment] 2016-03-03 23:07
On Thu, Mar 3, 2016 at 5:32 PM, Paul J. Durack <notifications@github.com>
wrote:

> @CendioOssman <https://github.com/CendioOssman> is my testing it appears
> that the instances of clipboard failure have reduced, but there are still
> some quirky cases where I need to copy items twice before they correctly
> map back and forth into the client
>
Can you try increasing the polling frequency (ie: vncconfig -poll 250) to
see if those go away?

**Comment by durack1** [comment] 2016-03-04 00:08
@bphinz I'll update the polling frequency and keep testing.. I'll try and report back sometime next week.

**Comment by rdicroce** [comment] 2016-05-04 22:25
I just encountered this problem on a recent-ish snapshot build. Passing -poll 250 did not help. However, I did get the clipboard to work consistently by using autocutsel instead of vncconfig. So I suspect the problem is in vncconfig and not the clients.

**Comment by durack1** [comment] 2016-05-17 16:27
@bphinz @CendioOssman apologies for the radio silence on this.. Did you guys require some additional diagnostics?

**Comment by CendioOssman** [comment] 2016-05-18 07:38
Yes, we're waiting for you to report if the polling helped or not. :)

**Comment by CendioOssman** [comment] 2016-05-18 07:40
It would also help if you could describe a test case, i.e. which application are you using, which version, and the exact steps you perform.

**Comment by durack1** [comment] 2016-05-20 00:53
@CendioOssman yes the polling seemed to improve things considerably..

I did change my environment considerably (updated the RealVNC client from 5.2.3 to 5.3.0, which caused problems) and then following your suggestions moved to the TigerVNC client.. So I'm not sure I didn't fix the issue with more than just the updated `vncconfig -nowin -poll 250` command..

What specific tests would you like me to perform? I have a RealVNC client updated to 5.3.1 and am currently using TigerVNC 1.6.0 as my default client..

**Comment by CendioOssman** [comment] 2016-05-23 08:56
Please use our client so we don't have to also worry about bugs in their code. :)

Do any test you like where you can easily reproduce the bug. The simpler the better though. Then we can see if we can repeat the issue here.

**Comment by durack1** [comment] 2016-05-23 17:47
@CendioOssman no problem - I'll start collecting some different usage patterns and see if I can replicate my issue reliably enough to send you a step-by-step

**Comment by durack1** [comment] 2016-07-01 23:16
@CendioOssman thanks again for the prompt, we had a number of machine failures and required rebuilding. I now have a couple of machines RHEL6.8 and RHEL7.2 that I will be using intensively over the following months, I've patched these both up to `1.6.0` and am also running the `1.6.0` client locally so if there is a standing issue, I should encounter it soon.. I'll update this if/when I encounter issues..

**Comment by erkkiruohtula** [comment] 2016-10-10 11:13
Just a note I'm seeing this, too. Copy-paste always works from server (Fedora 24, tigervnc-server 1.6.0) to TigerVNC client on Windows 7 (version 1.6.0), but never in the other direction. "vncconfig -poll" makes no difference.

**Comment by CendioOssman** [comment] 2016-10-17 06:36
That does not sound like the same issue. Can you test from a different client? Ideally also using a different OS.

**Comment by erkkiruohtula** [comment] 2016-10-24 05:55
@CendioOssman sorry for the delay (vacation). I tried to copy-paste with RealVNC client version 5.0.5 still on Windows 7, and with it, the operation worked fine in both directions. The server end was the same (TigerVNC 1.6.0 on Fedora24).

**Comment by erkkiruohtula** [comment] 2016-10-24 06:03
@CendioOssman as another test, connected to the same server from a CentOS 7 with TigerVNC client 1.3.1 (the version that comes with CentOS 7), and in this combination copy-paste also works in both directions. Hope this helps.

**Comment by CendioOssman** [comment] 2016-10-24 13:11
Not the same issue then as yours seems to be a client issue. Please open a separate entry.

**Comment by CendioOssman** [comment] 2017-02-24 09:05
No update, so I'll assume this got resolved. :)

**Closed by CendioOssman** 2017-02-24 09:05 UTC

**Comment by durack1** [comment] 2017-02-24 15:33
Thanks @CendioOssman once I started using the tigervnc client the issue disappeared for me..

**Comment by skpcoding** [comment] 2017-10-06 23:55
Hello Experts, 
I am connecting from Mac Sierra to a Linux x64. My Mac VNC client is Tiger VNC Viewer 1.8.0 and VNC server is Tiger VNC 1.1.0. 

I can copy texts from Linux box to local Mac as below ( over tiger VNC):
- highlight the text on Linux
- with Command + C copy 
- and can paste on local Mac with Command +v 

But I can not copy/paste the text from Linux to same Linux box.
Also it's not working for copying text from Mac to Linux. 

How can I paste something on remote Linux that's copied on remote Linux box or copied from local Mac ( over Tiger VNC)?


Thank you in advance.

**Comment by CendioOssman** [comment] 2017-10-09 08:18
Please open a new issue as the original one was resolved. Also, please try the latest version of TigerVNC first.

**Comment by ucguy4u** [comment] 2020-09-15 05:56
On the right corner of the Linux, the scissor is located. right-click and close the default clipboard manager and then start with Tigervnc clipboard manager as :

    $ vncconfig &

It will start the TigerVNC clipboard. So you can share the clipboard with the local and remote machine.

I have tested and worked this on Oracle Linux.

**Comment by danilaml** [comment] 2021-05-21 13:34
Hm, after update to 1.8.0 copies from Host to remote no longer works for me (on CentOS 7). The opposite direction works fine. With or without vncconfig. There is no `-poll` option either.
